#!/bin/bash
# Quick setup script for French translation

echo "🇫🇷 French Flashcard Translation Setup"
echo "======================================"
echo ""
echo "This will translate all 100 parts of Seerah flashcards to French."
echo ""
echo "Step 1: Get an Anthropic API key"
echo "  Visit: https://console.anthropic.com/"
echo "  Sign up (free tier available)"
echo "  Copy your API key"
echo ""
echo "Step 2: Set your API key"
echo "  Windows PowerShell:"
echo "    \$env:ANTHROPIC_API_KEY='sk-ant-your-key-here'"
echo "  Linux/Mac:"
echo "    export ANTHROPIC_API_KEY='sk-ant-your-key-here'"
echo ""
echo "Step 3: Run the translation"
echo "  node scripts/fr-source/complete-translation.mjs"
echo ""
echo "Estimated time: 15-20 minutes"
echo "Estimated cost: \$3-5 USD"
echo ""
echo "======================================"
