/**
 * French titles + subtitles for all 100 Seerah parts.
 * Used when course language is "fr" — English PARTS in content.ts stay the source of truth for EN.
 */

export const PART_TITLES_FR: Record<number, { title: string; subtitle: string }> = {
  1:  { title: "Le contexte arabique préislamique",              subtitle: "Poser le décor" },
  2:  { title: "Les tribus arabes et leurs migrations",           subtitle: "Origines d'un peuple" },
  3:  { title: "Structures politiques du Yémen préislamique",     subtitle: "Royaumes du Sud" },
  4:  { title: "Le royaume de Hîra",                              subtitle: "Un État tampon arabo-perse" },
  5:  { title: "Les Ghassânides de Syrie",                        subtitle: "Clients arabes de Byzance" },
  6:  { title: "Les gardiens de La Mecque avant l'islam",         subtitle: "La custodie de la Cité sacrée" },
  7:  { title: "Du monothéisme à l'idolâtrie",                    subtitle: "Comment l'Arabie perdit la foi d'Ibrahim ﷺ" },
  8:  { title: "Le paysage religieux de l'Arabie préislamique",   subtitle: "Une tapisserie complexe de croyances" },
  9:  { title: "La société arabique préislamique",                subtitle: "Tribus, honneur et coutume" },
  10: { title: "Le monde socio-économique avant l'islam",         subtitle: "Pauvreté, commerce et éthique" },

  11: { title: "La lignée du Prophète ﷺ",                        subtitle: "Une noble chaîne d'ascendance" },
  12: { title: "La famille de Hâshim",                            subtitle: "Custodes de La Mecque" },
  13: { title: "La jeunesse du Prophète ﷺ",                      subtitle: "Une enfance sous la protection divine" },
  14: { title: "Le caractère de Muhammad ﷺ avant la prophétie",  subtitle: "Al-Amîn — le Digne de confiance" },

  15: { title: "La première révélation",                         subtitle: "Iqra ! — La nuit qui changea le monde" },
  16: { title: "La nature de la révélation prophétique",          subtitle: "Comment le Coran fut descendu" },
  17: { title: "Les premières phases de l'appel à l'islam",       subtitle: "Une mission secrète à La Mecque" },
  18: { title: "L'appel islamique et l'établissement de la prière", subtitle: "Les premiers rites du culte" },
  19: { title: "Le passage à la prédication ouverte",             subtitle: "Annoncer le message publiquement" },
  20: { title: "La proclamation publique à La Mecque",            subtitle: "Quraysh entend l'appel" },

  21: { title: "Les stratégies d'opposition de Quraysh",          subtitle: "Comment ils combattirent le message" },
  22: { title: "La persécution des premiers musulmans",           subtitle: "Le prix de la foi" },
  23: { title: "Stratégies musulmanes : secret et migration",     subtitle: "Survivre à La Mecque" },
  24: { title: "La campagne de Quraysh contre l'islam en Abyssinie", subtitle: "La bataille diplomatique à l'étranger" },
  25: { title: "L'escalade des hostilités à La Mecque",           subtitle: "Quand les mots ne suffisaient plus" },
  26: { title: "La conversion de Hamza et de ʿUmar رضي الله عنهما", subtitle: "Deux géants embrassent l'islam" },
  27: { title: "Stratégies évolutives de Quraysh et politique des clans", subtitle: "Les dynamiques internes de l'opposition" },
  28: { title: "Le boycott de Banû Hâshim par Quraysh",           subtitle: "Trois années de siège et de famine" },
  29: { title: "Les négociations finales à La Mecque",            subtitle: "Dernières tentatives de compromis de Quraysh" },
  30: { title: "L'année de la tristesse",                         subtitle: "La mort de Khadîja et d'Abû Tâlib" },
  31: { title: "Le voyage à Tâ'if",                               subtitle: "Rejet et miséricorde divine" },
  32: { title: "La daʿwa pré-hégirienne à La Mecque",             subtitle: "Chercher une nouvelle demeure pour l'islam" },
  33: { title: "La onzième année de la prophétie",                subtitle: "À la veille du grand changement" },
  34: { title: "L'Isrâ' et le Miʿrâj",                            subtitle: "Le voyage nocturne et l'ascension" },

  35: { title: "Le premier serment d'al-ʿAqaba",                  subtitle: "Yathrib répond à l'appel" },
  36: { title: "Le second serment d'al-ʿAqaba",                   subtitle: "Un pacte de protection" },
  37: { title: "Le complot de Quraysh et la décision d'émigrer",  subtitle: "La nuit du départ" },
  38: { title: "La Hégire vers Médine",                           subtitle: "Un voyage qui changea le monde" },

  39: { title: "Les fondements de la communauté médinoise",       subtitle: "Bâtir une nouvelle civilisation" },
  40: { title: "La fondation de la société islamique à Médine",   subtitle: "Fraternité, mosquée et marché" },
  41: { title: "La Charte et les fondements éthiques de Médine",  subtitle: "Un nouvel ordre social" },
  42: { title: "Le pacte de Médine",                              subtitle: "L'islam et les relations intercommunautaires" },
  43: { title: "Le passage à la défense armée",                   subtitle: "Quand le combat devint licite" },
  44: { title: "Développements militaires et politiques avant Badr", subtitle: "La scène est dressée" },

  45: { title: "La bataille de Badr",                             subtitle: "Le jour du discernement" },
  46: { title: "Badr : une redéfinition de la loyauté",           subtitle: "Qui se tint avec Allah ?" },
  47: { title: "Les lendemains de Badr",                          subtitle: "Prisonniers, rançon et conséquences" },
  48: { title: "L'environnement stratégique après Badr",          subtitle: "Un paysage transformé" },
  49: { title: "Le paysage politique et social après Badr",       subtitle: "La nouvelle réalité de Médine" },
  50: { title: "Conflits post-Badr : Banû Qaynuqâʿ et l'expédition de Sawîq", subtitle: "Les braises de l'opposition" },
  51: { title: "Actions communautaires au début de la troisième année de l'Hégire", subtitle: "Consolider l'Oumma" },
  52: { title: "Confrontations militaires précédant Uhud",        subtitle: "Quraysh prépare sa vengeance" },
  53: { title: "La bataille d'Uhud : mobilisation et stratégie",  subtitle: "Les armées se rassemblent" },
  54: { title: "Préparatifs de la bataille d'Uhud",               subtitle: "L'armée du Prophète prend forme" },
  55: { title: "Disposition des forces à Uhud",                   subtitle: "Stratégie au pied de la montagne" },
  56: { title: "L'ouverture de la bataille d'Uhud",               subtitle: "Un engagement décisif commence" },
  57: { title: "Le grand retournement d'Uhud",                    subtitle: "Comment la victoire devint défaite" },
  58: { title: "La défense du Prophète ﷺ à Uhud",                subtitle: "Des cœurs qui ne fléchirent pas" },
  59: { title: "Les lendemains de la bataille d'Uhud",            subtitle: "Deuil, leçons et résolution" },
  60: { title: "L'expédition de Hamrâ' al-Asad",                  subtitle: "Une démonstration de force après la défaite" },
  61: { title: "Engagements militaires après Uhud",               subtitle: "Les batailles qui suivirent" },
  62: { title: "Développements militaires et diplomatiques des années 4–5 de l'Hégire", subtitle: "Le paysage continue de changer" },
  63: { title: "La bataille des Coalisés",                        subtitle: "Dix mille aux portes de Médine" },
  64: { title: "L'expédition contre Banû Qurayza",                subtitle: "Responsabilité et justice" },
  65: { title: "La ghazwa de Banû al-Mustaliq",                   subtitle: "L'hypocrisie dévoilée" },
  66: { title: "Opérations stratégiques et diplomatiques en l'an 6 de l'Hégire", subtitle: "Manœuvres avant al-Hudaybiyya" },
  67: { title: "Le traité d'al-Hudaybiyya",                       subtitle: "Une victoire claire déguisée" },
  68: { title: "L'impact socio-politique d'al-Hudaybiyya",        subtitle: "Un traité qui transforma l'Arabie" },
  69: { title: "Stratégie post-Hudaybiyya et rayonnement diplomatique", subtitle: "L'islam s'ouvre au monde" },
  70: { title: "Correspondance avec l'Égypte : le Muqawqis",      subtitle: "Lettres aux puissants" },
  71: { title: "Lettres à Kisrâ et aux dirigeants du Yémen",      subtitle: "L'Orient et le Sud reçoivent l'appel" },
  72: { title: "La lettre prophétique à Héraclius",               subtitle: "César confronté à l'islam" },
  73: { title: "Correspondance avec al-Bahrayn",                  subtitle: "La réponse de l'Arabie orientale" },
  74: { title: "Correspondance avec al-Yamâma",                   subtitle: "Le cœur de l'Arabie sollicité" },
  75: { title: "La lettre à al-Hârith al-Ghassânî",               subtitle: "La Syrie entend l'appel" },
  76: { title: "Diplomatie prophétique : les rois d'Oman",        subtitle: "Le royaume maritime reçoit le message" },
  77: { title: "L'expédition de Dhû Qarad",                       subtitle: "Défendre les abords de Médine" },
  78: { title: "La conquête de Khaybar",                           subtitle: "La chute des forteresses" },
  79: { title: "La campagne de Khaybar : analyse stratégique",    subtitle: "Une nouvelle phase de puissance" },
  80: { title: "Conquête de Khaybar : suites et héritage",        subtitle: "Ce que Khaybar changea" },
  81: { title: "Campagnes militaires après la coalition",         subtitle: "Ouvrir la voie vers La Mecque" },
  82: { title: "Expéditions du Nord en l'an 8 de l'Hégire",       subtitle: "Prélude à la grande conquête" },

  83: { title: "La route vers la conquête de La Mecque",          subtitle: "Le traité rompu, l'heure est venue" },
  84: { title: "La conquête de La Mecque",                        subtitle: "Vingt ans bouclent la boucle" },
  85: { title: "Les batailles de Hunayn et de Tâ'if",             subtitle: "L'orgueil avant la chute, la miséricorde dans la victoire" },
  86: { title: "La distribution à al-Jiʿrâna",                    subtitle: "Sagesse au lendemain de la victoire" },
  87: { title: "Après Hunayn : la délégation de Hawâzin",         subtitle: "Miséricorde et pardon" },
  88: { title: "Consolidation stratégique en l'an 9 de l'Hégire", subtitle: "Une péninsule unie sous l'islam" },
  89: { title: "L'expédition de Tabûk : une réponse à Byzance",   subtitle: "Marcher vers le Nord, jusqu'à la frontière" },
  90: { title: "L'expédition de Tabûk : Jaysh al-ʿUsra",           subtitle: "L'armée de la difficulté" },
  91: { title: "L'expédition de Tabûk : conséquences et révélations", subtitle: "Ce que Tabûk révéla" },
  92: { title: "La proclamation de Barâ'a",                       subtitle: "Le Hajj de la neuvième année et la fin du shirk à La Mecque" },
  93: { title: "Les campagnes militaires du Prophète ﷺ : leadership et éthique", subtitle: "Un héritage de justice" },
  94: { title: "L'entrée massive dans l'islam",                   subtitle: "Toute l'Arabie embrasse la foi" },
  95: { title: "L'année des délégations",                         subtitle: "Les tribus viennent à Médine" },
  96: { title: "L'impact et l'héritage de l'appel islamique",     subtitle: "Une mission qui refaçonna le monde" },
  97: { title: "Le pèlerinage d'adieu",                           subtitle: "Le dernier Hajj du Prophète ﷺ" },
  98: { title: "L'expédition d'Usâma ibn Zayd",                   subtitle: "Un dernier ordre à ses Compagnons" },
  99: { title: "Les derniers jours du Prophète ﷺ",               subtitle: "Le Bien-Aimé s'en va" },
  100:{ title: "La famille du Prophète ﷺ",                        subtitle: "Ceux qu'il laissa derrière lui" },
};

export const ERA_LABELS_FR: Record<string, { label: string; description: string }> = {
  "pre-islamic":       { label: "L'Arabie préislamique", description: "Le monde avant la révélation finale" },
  "birth-early-life":  { label: "Naissance et jeunesse", description: "La venue du Prophète ﷺ" },
  "early-revelation":  { label: "Début de la révélation", description: "La première lumière de l'islam" },
  "makkah-persecution":{ label: "La Mecque — Persécution", description: "Années d'épreuve et de fermeté" },
  "hijrah":            { label: "La Hégire", description: "La grande migration qui changea l'histoire" },
  "madinah":           { label: "La période médinoise", description: "Bâtir la première société musulmane" },
  "campaigns":         { label: "Les grandes campagnes", description: "Épreuves et triomphes de l'Oumma" },
  "final-years":       { label: "Dernières années et héritage", description: "L'adieu et l'impact éternel" },
};
