import type { CourseLang } from "./course-lang";

/**
 * Shared UI string dictionary for the student course shell.
 * Usage: t(lang, "key") or tf(lang, "key", { n: 5 }) for interpolated strings.
 */

const S = {
  // ─── Dashboard tabs ──────────────────────────────────────────────────────────
  tabDashboard:      { en: "Dashboard", ar: "الرئيسية", fr: "Tableau de bord" },
  tabHome:           { en: "Home", ar: "الرئيسية", fr: "Accueil" },
  tabLessons:        { en: "Lessons", ar: "الدروس", fr: "Leçons" },
  tabResources:      { en: "Resources", ar: "الموارد", fr: "Ressources" },
  tabMedia:          { en: "Media", ar: "الوسائط", fr: "Médias" },
  tabReference:      { en: "Reference", ar: "المرجع", fr: "Référence" },
  tabRef:            { en: "Ref", ar: "مرجع", fr: "Réf." },
  tabProgress:       { en: "Progress", ar: "التقدم", fr: "Progression" },
  tabStats:          { en: "Stats", ar: "إحصائيات", fr: "Stats" },
  tabAcct:           { en: "Acct", ar: "الحساب", fr: "Compte" },
  openAccountMenu:   { en: "Open account menu", ar: "فتح قائمة الحساب", fr: "Ouvrir le menu du compte" },
  courseSections:    { en: "Course sections", ar: "أقسام الدورة", fr: "Sections du cours" },

  // ─── Home content ─────────────────────────────────────────────────────────
  welcomeBack:       { en: "Welcome back", ar: "مرحبًا بعودتك", fr: "Bon retour" },
  part1Free:         { en: "Part 1 is free — begin the Seerah today.", ar: "الجزء الأول مجاني — ابدأ السيرة النبوية اليوم.", fr: "La partie 1 est gratuite — commencez la Sîra dès aujourd'hui." },
  freeStartHere:     { en: "Free — Start Here", ar: "مجاني — ابدأ من هنا", fr: "Gratuit — Commencez ici" },
  startHere:         { en: "Start here", ar: "ابدأ من هنا", fr: "Commencez ici" },
  continueLearning:  { en: "Continue learning", ar: "استمر في التعلم", fr: "Continuer l'apprentissage" },
  partN:             { en: "Part {n}", ar: "الجزء {n}", fr: "Partie {n}" },
  stageNofM:         { en: "Stage {n} of {m}", ar: "المرحلة {n} من {m}", fr: "Étape {n} sur {m}" },
  minRead:           { en: "15–20 min", ar: "١٥–٢٠ دقيقة", fr: "15–20 min" },
  bestStartingPoint: { en: "Best starting point", ar: "أفضل نقطة بداية", fr: "Meilleur point de départ" },
  lessonProgress:    { en: "Lesson progress", ar: "تقدم الدرس", fr: "Progression de la leçon" },
  startPartN:        { en: "Start Part {n}", ar: "ابدأ الجزء {n}", fr: "Commencer la partie {n}" },
  continuLesson:     { en: "Continue Lesson", ar: "استمر في الدرس", fr: "Continuer la leçon" },
  viewRoadmap:       { en: "View Roadmap", ar: "عرض خريطة الدورة", fr: "Voir le parcours" },
  howToUseLesson:    { en: "How to use each lesson", ar: "كيف تستخدم كل درس", fr: "Comment utiliser chaque leçon" },
  allFormatsRetention:{ en: "All four formats together for best retention", ar: "الجمع بين الأشكال الأربعة لأفضل نتيجة", fr: "Les quatre formats ensemble pour une meilleure mémorisation" },
  watchTheVideo:     { en: "Watch the video", ar: "شاهد الفيديو", fr: "Regarder la vidéo" },
  readTheBriefing:   { en: "Read the briefing", ar: "اقرأ الملخص", fr: "Lire le briefing" },
  reviewFlashcards:  { en: "Review flashcards", ar: "راجع البطاقات التعليمية", fr: "Réviser les flashcards" },
  takeTheQuiz:       { en: "Take the quiz", ar: "أجرِ الاختبار", fr: "Passer le quiz" },
  unlockAllN:        { en: "Unlock All {n} Parts", ar: "افتح جميع الـ {n} جزءًا", fr: "Débloquer les {n} parties" },
  unlockDesc:        { en: "Get lifetime access to the full Seerah course — videos, reading notes, flashcards, and quizzes for every part.", ar: "احصل على وصول مدى الحياة إلى دورة السيرة النبوية الكاملة — فيديوهات وملخصات وبطاقات تعليمية واختبارات لكل جزء.", fr: "Obtenez un accès à vie au cours complet de Sîra — vidéos, notes de lecture, flashcards et quiz pour chaque partie." },
  viewPlans:         { en: "View Plans", ar: "عرض الخطط", fr: "Voir les formules" },
  completedStat:     { en: "Completed", ar: "مكتملة", fr: "Terminées" },
  partsFullyCompleted:{ en: "Parts fully completed", ar: "أجزاء مكتملة بالكامل", fr: "Parties entièrement terminées" },
  requiresQuiz:      { en: "Requires passing the quiz (80%+)", ar: "يتطلب اجتياز الاختبار (٨٠٪+)", fr: "Nécessite de réussir le quiz (80 %+)" },
  currentStage:      { en: "Current Stage", ar: "المرحلة الحالية", fr: "Étape actuelle" },
  nextLesson:        { en: "Next Lesson", ar: "الدرس التالي", fr: "Leçon suivante" },
  startNow:          { en: "Start now", ar: "ابدأ الآن", fr: "Commencer maintenant" },
  continue:          { en: "Continue", ar: "استمر", fr: "Continuer" },
  courseRoadmap:     { en: "Course Roadmap", ar: "خريطة الدورة", fr: "Parcours du cours" },
  seerahInStages:    { en: "The Seerah in {n} stages — from pre-Islamic Arabia to the Prophet\u2019s \ufdfa final years. Each part unlocks after you complete the previous lesson\u2019s quiz. Follow the order for the full picture.", ar: "السيرة النبوية في {n} مراحل — من الجزيرة العربية قبل الإسلام حتى السنوات الأخيرة من حياة النبي ﷺ.", fr: "La Sîra en {n} étapes — de l'Arabie préislamique aux dernières années du Prophète \ufdfa. Chaque partie se débloque après le quiz de la leçon précédente. Suivez l'ordre pour une vision d'ensemble." },
  currentStageLabel: { en: "▸ Current", ar: "▸ الحالية", fr: "▸ Actuelle" },
  stageN:            { en: "Stage {n}", ar: "المرحلة {n}", fr: "Étape {n}" },
  review:            { en: "Review", ar: "راجع", fr: "Réviser" },
  start:             { en: "Start", ar: "ابدأ", fr: "Commencer" },
  quickAccessTools:  { en: "Quick Access to Course Tools", ar: "الوصول السريع إلى أدوات الدورة", fr: "Accès rapide aux outils du cours" },
  everyPartIncludes: { en: "Every part includes all of these formats. Use them in any order.", ar: "كل جزء يشمل هذه الأشكال جميعًا. استخدمها بأي ترتيب.", fr: "Chaque partie comprend tous ces formats. Utilisez-les dans l'ordre de votre choix." },
  watchLessons:      { en: "Watch Lessons", ar: "شاهد الدروس", fr: "Regarder les leçons" },
  readBriefings:     { en: "Read Briefings", ar: "اقرأ الملخصات", fr: "Lire les briefings" },
  listenOnTheGo:     { en: "Listen on the Go", ar: "استمع أثناء التنقل", fr: "Écouter en déplacement" },
  slides:            { en: "Slides", ar: "الشرائح", fr: "Diapositives" },
  infographics:      { en: "Infographics", ar: "الرسوم المعلوماتية", fr: "Infographies" },
  mindMaps:          { en: "Mind Maps", ar: "الخرائط الذهنية", fr: "Cartes mentales" },
  flashcards:        { en: "Flashcards", ar: "البطاقات التعليمية", fr: "Flashcards" },
  quizzes:           { en: "Quizzes", ar: "الاختبارات", fr: "Quiz" },
  needHelp:          { en: "Need help getting started?", ar: "هل تحتاج إلى مساعدة؟", fr: "Besoin d'aide pour commencer ?" },
  helpDesc:          { en: "If something does not load, or you are unsure where to begin, contact support.", ar: "إذا لم يتم تحميل شيء، أو لم تعرف من أين تبدأ، تواصل مع الدعم.", fr: "Si quelque chose ne se charge pas, ou si vous ne savez pas par où commencer, contactez le support." },
  contactSupport:    { en: "Contact Support", ar: "تواصل مع الدعم", fr: "Contacter le support" },

  // ─── Progress page ────────────────────────────────────────────────────────
  yourProgress:      { en: "Your Progress", ar: "تقدمك", fr: "Votre progression" },
  journeyDesc:       { en: "Your journey through the Complete Seerah course.", ar: "رحلتك عبر دورة السيرة النبوية الكاملة.", fr: "Votre parcours dans le cours Complet de la Sîra." },
  startLearning:     { en: "Start Learning", ar: "ابدأ التعلم", fr: "Commencer à apprendre" },
  beginPart1:        { en: "Begin Part 1 of the Seerah", ar: "ابدأ الجزء الأول من السيرة", fr: "Commencer la partie 1 de la Sîra" },
  continueLearningBtn:{ en: "Continue Learning", ar: "استمر في التعلم", fr: "Continuer l'apprentissage" },
  progressStat:      { en: "Progress", ar: "التقدم", fr: "Progression" },
  notStartedYet:     { en: "Not started yet", ar: "لم تبدأ بعد", fr: "Pas encore commencé" },
  ofFullSeerah:      { en: "of the full Seerah", ar: "من السيرة الكاملة", fr: "de la Sîra complète" },
  avgQuizScore:      { en: "Avg Quiz Score", ar: "متوسط الاختبارات", fr: "Score moyen aux quiz" },
  attempts1:         { en: "{n} attempt", ar: "{n} محاولة", fr: "{n} tentative" },
  attemptsN:         { en: "{n} attempts", ar: "{n} محاولات", fr: "{n} tentatives" },
  noQuizzesYet:      { en: "No quizzes attempted yet", ar: "لم يُحاول في أي اختبار بعد", fr: "Aucun quiz tenté pour l'instant" },
  howPartsCompleted: { en: "How parts are counted as completed", ar: "كيف تُحسب الأجزاء المكتملة", fr: "Comment les parties sont comptées comme terminées" },
  passQuizWith80:    { en: "Pass the Quiz with 80% or higher", ar: "اجتاز الاختبار بنسبة ٨٠٪ فأكثر", fr: "Réussir le quiz avec 80 % ou plus" },
  stageProgress:     { en: "Stage Progress", ar: "تقدم المراحل", fr: "Progression des étapes" },
  nStages:           { en: "{n} stages", ar: "{n} مراحل", fr: "{n} étapes" },
  recentlyOpened:    { en: "Recently Opened", ar: "مفتوحة مؤخرًا", fr: "Ouverts récemment" },
  noActivityYet:     { en: "No activity yet", ar: "لا يوجد نشاط بعد", fr: "Aucune activité pour l'instant" },
  startPart1Prompt:  { en: "Start Part 1 and your recent lessons will appear here.", ar: "ابدأ الجزء الأول وستظهر دروسك الأخيرة هنا.", fr: "Commencez la partie 1 et vos leçons récentes apparaîtront ici." },
  startPart1:        { en: "Start Part 1", ar: "ابدأ الجزء الأول", fr: "Commencer la partie 1" },
  nPartsCompleted:   { en: "{n} part{s} completed", ar: "{n} جزء مكتمل", fr: "{n} partie{s} terminée(s)" },
  viewLink:          { en: "View", ar: "عرض", fr: "Voir" },
  inProgress:        { en: "In Progress", ar: "جاري", fr: "En cours" },

  // ─── Lessons path ─────────────────────────────────────────────────────────
  lessonsHeader:     { en: "Lessons", ar: "الدروس", fr: "Leçons" },
  lessonsSubheader:  { en: "The complete Seerah of the Prophet \ufdfa in 100 parts, arranged chronologically.", ar: "السيرة النبوية الكاملة في ١٠٠ جزء، مرتبة تاريخيًا.", fr: "La Sîra complète du Prophète \ufdfa en 100 parties, classées chronologiquement." },
  locked:            { en: "Locked", ar: "مقفل", fr: "Verrouillé" },
  assetVideo:        { en: "Video", ar: "الفيديو", fr: "Vidéo" },
  assetBriefing:     { en: "Briefing", ar: "الملخص", fr: "Briefing" },
  assetSlides:       { en: "Slides", ar: "الشرائح", fr: "Diapositives" },
  assetAudio:        { en: "Audio", ar: "الصوت", fr: "Audio" },
  assetMindmap:      { en: "Mind Map", ar: "الخريطة الذهنية", fr: "Carte mentale" },
  assetFlashcards:   { en: "Flashcards", ar: "بطاقات تعليمية", fr: "Flashcards" },
  assetQuiz:         { en: "Quiz", ar: "الاختبار", fr: "Quiz" },
  nParts:            { en: "{n} {part}", ar: "{n} جزء", fr: "{n} {part}" },

  // ─── Resources hub (course-resources-content) ─────────────────────────────
  yourResources:     { en: "Your Resources", ar: "مواردك", fr: "Vos ressources" },
  videoLessons:      { en: "Video Lessons", ar: "دروس الفيديو", fr: "Leçons vidéo" },
  videoLessonsDesc:  { en: "Watch all 100 guided video lessons", ar: "شاهد جميع الـ ١٠٠ درس", fr: "Regardez les 100 leçons vidéo guidées" },
  listenGoDesc:      { en: "Audio version of every lesson", ar: "النسخة الصوتية لكل درس", fr: "Version audio de chaque leçon" },
  briefings:         { en: "Briefings", ar: "الملخصات", fr: "Briefings" },
  briefingsDesc:     { en: "Read briefings for each part", ar: "اقرأ ملخص كل جزء", fr: "Lisez les briefings de chaque partie" },
  slidesDesc:        { en: "3 formats: Presented, Detailed, Facts", ar: "٣ أشكال: مقدَّمة، مفصَّلة، معلومات", fr: "3 formats : Présenté, Détaillé, Faits" },
  infographicsDesc:  { en: "3 formats: Concise, Standard, Bento Grid", ar: "٣ أشكال: موجزة، قياسية، شبكية", fr: "3 formats : Concis, Standard, Grille Bento" },
  mindMapsDesc:      { en: "Visual maps connecting people and events", ar: "خرائط مرئية تربط الأشخاص والأحداث", fr: "Cartes visuelles reliant personnes et événements" },
  flashcardsDesc:    { en: "Easy, Medium, and Hard flashcard sets", ar: "مجموعات سهلة ومتوسطة وصعبة", fr: "Jeux de flashcards Facile, Moyen et Difficile" },
  quizzesDesc:       { en: "Test your knowledge for each part", ar: "اختبر معلوماتك في كل جزء", fr: "Testez vos connaissances pour chaque partie" },
  reports:           { en: "Reports", ar: "التقارير", fr: "Rapports" },
  reportsDesc:       { en: "Comprehensive reports for each lesson", ar: "تقارير شاملة لكل درس", fr: "Rapports complets pour chaque leçon" },
  studyGuides:       { en: "Study Guides", ar: "أدلة الدراسة", fr: "Guides d'étude" },
  studyGuidesDesc:   { en: "Detailed study guides for review", ar: "أدلة دراسة تفصيلية للمراجعة", fr: "Guides d'étude détaillés pour la révision" },
  facts:             { en: "Facts", ar: "المعلومات", fr: "Faits" },
  factsDesc:         { en: "Quick reference facts for each part", ar: "معلومات مرجعية سريعة لكل جزء", fr: "Faits de référence rapide pour chaque partie" },

  // ─── Reference library ────────────────────────────────────────────────────
  referenceLibrary:  { en: "Reference Library", ar: "مكتبة المراجع", fr: "Bibliothèque de référence" },
  seerahReferenceLib:{ en: "Seerah Reference Library", ar: "مكتبة مراجع السيرة النبوية", fr: "Bibliothèque de référence de la Sîra" },
  referenceLibDesc:  { en: "Extra Seerah reference guides, timelines, people, places, and historical notes to help you understand the life of the Prophet \ufdfa more clearly.", ar: "مراجع إضافية، تسلسل زمني، شخصيات، أماكن وملاحظات تاريخية لفهم أعمق لسيرة النبي ﷺ.", fr: "Guides de référence supplémentaires, chronologies, personnages, lieux et notes historiques pour mieux comprendre la vie du Prophète \ufdfa." },
  backToRefLib:      { en: "Back to Reference Library", ar: "العودة إلى مكتبة المراجع", fr: "Retour à la bibliothèque de référence" },
  moreSectionsSoon:  { en: "More reference sections coming soon. Use these resources alongside your lessons to deepen your understanding of the Seerah.", ar: "مزيد من أقسام المراجع قريبًا. استخدم هذه الموارد مع دروسك لتعميق فهمك للسيرة النبوية.", fr: "D'autres sections de référence arriveront bientôt. Utilisez ces ressources avec vos leçons pour approfondir votre compréhension de la Sîra." },
  viewCard:          { en: "View {title}", ar: "عرض {title}", fr: "Voir {title}" },

  // Reference card titles + descriptions
  refFamilyTitle:    { en: "Family & Household", ar: "الأسرة والبيت", fr: "Famille et foyer" },
  refFamilyDesc:     { en: "A clear guide to the wives, children, and household of the Prophet \ufdfa, with simple tables and historical notes.", ar: "دليل واضح لزوجات النبي ﷺ وأبنائه وأسرته، مع جداول بسيطة وملاحظات تاريخية.", fr: "Un guide clair sur les épouses, les enfants et le foyer du Prophète \ufdfa, avec des tableaux simples et des notes historiques." },
  refTimelineTitle:  { en: "Timeline of the Seerah", ar: "التسلسل الزمني للسيرة", fr: "Chronologie de la Sîra" },
  refTimelineDesc:   { en: "A chronological timeline of major events in the life of the Prophet \ufdfa.", ar: "تسلسل زمني للأحداث الرئيسية في حياة النبي ﷺ.", fr: "Une chronologie des grands événements de la vie du Prophète \ufdfa." },
  refKeyPeopleTitle: { en: "Key People in the Seerah", ar: "أبرز شخصيات السيرة", fr: "Personnages clés de la Sîra" },
  refKeyPeopleDesc:  { en: "Companions, leaders, and figures whose roles shaped the early Muslim community.", ar: "الصحابة والقادة والشخصيات التي أثّرت في تشكيل المجتمع الإسلامي الأول.", fr: "Compagnons, dirigeants et figures dont les rôles ont façonné la première communauté musulmane." },
  refTribesTitle:    { en: "Tribes and Lineage", ar: "القبائل والنسب", fr: "Tribus et lignée" },
  refTribesDesc:     { en: "The major Arab tribes, their relationships, and the Prophet\u2019s \ufdfa lineage traced back.", ar: "أبرز القبائل العربية وعلاقاتها، ونسب النبي ﷺ.", fr: "Les grandes tribus arabes, leurs relations, et la lignée du Prophète \ufdfa retracée." },
  refPlacesTitle:    { en: "Places and Maps", ar: "الأماكن والخرائط", fr: "Lieux et cartes" },
  refPlacesDesc:     { en: "A reference to the key cities, routes, and locations mentioned in the Seerah.", ar: "مرجع لأهم المدن والطرق والمواقع المذكورة في السيرة.", fr: "Une référence aux principales villes, routes et lieux mentionnés dans la Sîra." },
  refBattlesTitle:   { en: "Battles and Expeditions", ar: "الغزوات والسرايا", fr: "Batailles et expéditions" },
  refBattlesDesc:    { en: "A clear reference to the major battles, campaigns, and expeditions of the Prophet \ufdfa.", ar: "مرجع واضح لأهم المعارك والحملات والغزوات.", fr: "Une référence claire aux grandes batailles, campagnes et expéditions du Prophète \ufdfa." },
  refMiraclesTitle:  { en: "Miracles and Signs", ar: "المعجزات والآيات", fr: "Miracles et signes" },
  refMiraclesDesc:   { en: "Verified narrations of miracles and signs granted to the Prophet \ufdfa.", ar: "روايات موثقة من معجزات وآيات النبي ﷺ.", fr: "Récits authentifiés de miracles et de signes accordés au Prophète \ufdfa." },
  refTermsTitle:     { en: "Important Terms", ar: "المصطلحات المهمة", fr: "Termes importants" },
  refTermsDesc:      { en: "A glossary of Arabic and historical terms used throughout the Seerah.", ar: "مسرد للمصطلحات العربية والتاريخية المستخدمة في السيرة.", fr: "Un glossaire des termes arabes et historiques utilisés dans la Sîra." },

  // ─── Resources library tabs ───────────────────────────────────────────────
  course:            { en: "Course", ar: "الدورة", fr: "Cours" },
  resources:         { en: "Resources", ar: "الموارد", fr: "Ressources" },
  breadcrumbLabel:   { en: "Breadcrumb", ar: "مسار التنقل", fr: "Fil d'Ariane" },
  resourceLibrary:   { en: "Resource Library", ar: "مكتبة الموارد", fr: "Bibliothèque de ressources" },
  resourceLibSubtitle:{ en: "All learning materials across the complete Seerah Masterclass", ar: "جميع المواد التعليمية لدورة السيرة النبوية الكاملة", fr: "Tous les supports d'apprentissage de la Masterclass complète de la Sîra" },
  videos:            { en: "Videos", ar: "الفيديوهات", fr: "Vidéos" },
  audio:             { en: "Audio", ar: "الصوت", fr: "Audio" },
  mindmapsTab:       { en: "Mindmaps", ar: "الخرائط الذهنية", fr: "Cartes mentales" },
  resourceTypes:     { en: "Resource types", ar: "أنواع الموارد", fr: "Types de ressources" },

  // ─── Resource filter bar ──────────────────────────────────────────────────
  searchLessons:     { en: "Search lessons...", ar: "ابحث عن الدروس...", fr: "Rechercher des leçons..." },
  clearSearch:       { en: "Clear search", ar: "مسح البحث", fr: "Effacer la recherche" },
  toggleFilters:     { en: "Toggle filters", ar: "تبديل الفلاتر", fr: "Afficher/masquer les filtres" },
  stageEra:          { en: "Stage / Era", ar: "المرحلة / العصر", fr: "Étape / Époque" },
  allStages:         { en: "All Stages", ar: "جميع المراحل", fr: "Toutes les étapes" },
  status:            { en: "Status", ar: "الحالة", fr: "Statut" },
  all:               { en: "All", ar: "الكل", fr: "Tous" },
  completedFilter:   { en: "Completed", ar: "المكتملة", fr: "Terminées" },
  inProgressFilter:  { en: "In Progress", ar: "جارية", fr: "En cours" },
  notStarted:        { en: "Not Started", ar: "لم تُبدأ", fr: "Non commencées" },
  clearFilters:      { en: "Clear filters", ar: "مسح الفلاتر", fr: "Effacer les filtres" },

  // ─── Video resource content ───────────────────────────────────────────────
  videoLessonsH1:    { en: "Video Lessons", ar: "دروس الفيديو", fr: "Leçons vidéo" },
  allNLessons:       { en: "All {n} guided lessons from the Seerah Masterclass", ar: "جميع الـ {n} درسًا الإرشادية", fr: "Les {n} leçons guidées de la Masterclass de la Sîra" },
  nOfMCompleted:     { en: "{n} of {m} video lessons completed · continue building your Seerah timeline", ar: "{n} من {m} درسًا مكتملًا · واصل بناء مسيرتك", fr: "{n} sur {m} leçons vidéo terminées · continuez à construire votre chronologie de la Sîra" },
  statTotal:         { en: "Total", ar: "المجموع", fr: "Total" },
  statCompleted:     { en: "Completed", ar: "مكتملة", fr: "Terminées" },
  statInProgress:    { en: "In Progress", ar: "جارية", fr: "En cours" },
  statNotStarted:    { en: "Not Started", ar: "لم تُبدأ", fr: "Non commencées" },
  continueWatching:  { en: "Continue Watching", ar: "استمر في المشاهدة", fr: "Continuer à regarder" },
  nPctWatched:       { en: "{n}% watched", ar: "{n}٪ تمت مشاهدته", fr: "{n} % visionnés" },
  resume:            { en: "Resume", ar: "استمر", fr: "Reprendre" },
  closeVideo:        { en: "Close video", ar: "إغلاق الفيديو", fr: "Fermer la vidéo" },
  done:              { en: "Done", ar: "مكتمل", fr: "Terminé" },
  partLabel:         { en: "Part {n}", ar: "الجزء {n}", fr: "Partie {n}" },
  resumePartAriaLabel: { en: "Resume Part {n}: {title}", ar: "استمر في الجزء {n}: {title}", fr: "Reprendre la partie {n} : {title}" },

  // ─── Audio resource content ───────────────────────────────────────────────
  allNAudio:         { en: "All {n} audio lessons from the Seerah Masterclass", ar: "جميع الـ {n} درسًا الصوتية", fr: "Les {n} leçons audio de la Masterclass de la Sîra" },
  nowPlaying:        { en: "Now Playing", ar: "يُشغَّل الآن", fr: "En cours de lecture" },
  audioNotAvail:     { en: "Audio not available for this lesson", ar: "الصوت غير متاح لهذا الدرس", fr: "Audio non disponible pour cette leçon" },
  listenNow:         { en: "Listen", ar: "استمع", fr: "Écouter" },
  closeAudio:        { en: "Close audio player", ar: "إغلاق مشغل الصوت", fr: "Fermer le lecteur audio" },
  previousTrack:     { en: "Previous track", ar: "المقطع السابق", fr: "Piste précédente" },
  nextTrack:         { en: "Next track", ar: "المقطع التالي", fr: "Piste suivante" },
  mute:              { en: "Mute", ar: "كتم الصوت", fr: "Couper le son" },
  unmute:            { en: "Unmute", ar: "رفع الصوت", fr: "Réactiver le son" },

  // ─── Text / quiz / simple resource content ────────────────────────────────
  nOfMRead:          { en: "{n} of {m} read", ar: "{n} من {m} مقروء", fr: "{n} sur {m} lus" },
  nOfMViewed:        { en: "{n} of {m} viewed", ar: "{n} من {m} تمت مشاهدته", fr: "{n} sur {m} consultés" },
  nOfMStudied:       { en: "{n} of {m} studied", ar: "{n} من {m} تمت دراسته", fr: "{n} sur {m} étudiés" },
  readNow:           { en: "Read", ar: "اقرأ", fr: "Lire" },
  viewNow:           { en: "View", ar: "عرض", fr: "Voir" },
  studyNow:          { en: "Study", ar: "ادرس", fr: "Étudier" },
  closeModal:        { en: "Close", ar: "إغلاق", fr: "Fermer" },
  statRead:          { en: "Read", ar: "مقروء", fr: "Lus" },
  statViewed:        { en: "Viewed", ar: "تمت مشاهدته", fr: "Consultés" },
  statStudied:       { en: "Studied", ar: "تمت دراسته", fr: "Étudiés" },
  statUnread:        { en: "Unread", ar: "غير مقروء", fr: "Non lus" },
  statNotViewed:     { en: "Not Viewed", ar: "لم تُشاهَد", fr: "Non consultés" },
  statNotStudied:    { en: "Not Studied", ar: "لم تُدرَس", fr: "Non étudiés" },
  noSlidesAvailable: { en: "No slides available", ar: "لا توجد شرائح متاحة", fr: "Aucune diapositive disponible" },
  resourceNotAvailable: { en: "Resource not available", ar: "المورد غير متاح", fr: "Ressource non disponible" },
  noFlashcardsAvailable: { en: "No flashcards available", ar: "لا توجد بطاقات تعليمية متاحة", fr: "Aucune flashcard disponible" },
  resetZoom:         { en: "Reset Zoom", ar: "إعادة ضبط التكبير", fr: "Réinitialiser le zoom" },
  scrollToZoomDragToPan: { en: "Scroll to zoom, drag to pan", ar: "مرّر للتكبير، واسحب للتحريك", fr: "Faites défiler pour zoomer, glissez pour déplacer" },
  clickToExitFullscreen: { en: "Click to exit fullscreen", ar: "اضغط للخروج من وضع ملء الشاشة", fr: "Cliquez pour quitter le plein écran" },
  clickToViewFullscreen: { en: "Click to view fullscreen", ar: "اضغط لعرض ملء الشاشة", fr: "Cliquez pour afficher en plein écran" },

  // ─── Quiz resource content ────────────────────────────────────────────────
  nOfMPassed:        { en: "{n} of {m} passed", ar: "{n} من {m} اجتازها", fr: "{n} sur {m} réussis" },
  avgScore:          { en: "Avg Score", ar: "متوسط الدرجات", fr: "Score moyen" },
  totalAttempts:     { en: "Total Attempts", ar: "إجمالي المحاولات", fr: "Tentatives totales" },
  passed:            { en: "Passed", ar: "اجتاز", fr: "Réussi" },
  failed:            { en: "Failed", ar: "لم يجتز", fr: "Échoué" },
  notAttempted:      { en: "Not Attempted", ar: "لم يُحاول", fr: "Non tenté" },
  takeQuiz:          { en: "Take Quiz", ar: "أجرِ الاختبار", fr: "Passer le quiz" },
  retakeQuiz:        { en: "Retake", ar: "أعد الاختبار", fr: "Repasser" },
  closeQuiz:         { en: "Close quiz", ar: "إغلاق الاختبار", fr: "Fermer le quiz" },

  // ─── Change password form ─────────────────────────────────────────────────
  changePassword:    { en: "Change Password", ar: "تغيير كلمة المرور", fr: "Changer le mot de passe" },
  currentPassword:   { en: "Current password", ar: "كلمة المرور الحالية", fr: "Mot de passe actuel" },
  enterCurrentPassword:{ en: "Enter current password", ar: "أدخل كلمة المرور الحالية", fr: "Saisir le mot de passe actuel" },
  newPassword:       { en: "New password", ar: "كلمة المرور الجديدة", fr: "Nouveau mot de passe" },
  atLeast8Chars:     { en: "At least 8 characters", ar: "٨ أحرف على الأقل", fr: "Au moins 8 caractères" },
  confirmNewPassword:{ en: "Confirm new password", ar: "تأكيد كلمة المرور الجديدة", fr: "Confirmer le nouveau mot de passe" },
  reenterNewPassword:{ en: "Re-enter new password", ar: "أعد إدخال كلمة المرور الجديدة", fr: "Ressaisir le nouveau mot de passe" },
  passwordsMatch:    { en: "Passwords match", ar: "كلمتا المرور متطابقتان", fr: "Les mots de passe correspondent" },
  passwordsDontMatch:{ en: "Passwords don't match", ar: "كلمتا المرور غير متطابقتين", fr: "Les mots de passe ne correspondent pas" },
  updated:           { en: "Updated", ar: "تم التحديث", fr: "Mis à jour" },
  saving:            { en: "Saving…", ar: "جارٍ الحفظ…", fr: "Enregistrement…" },
  updatePassword:    { en: "Update Password", ar: "تحديث كلمة المرور", fr: "Mettre à jour le mot de passe" },
  cancel:            { en: "Cancel", ar: "إلغاء", fr: "Annuler" },
  somethingWentWrong:{ en: "Something went wrong", ar: "حدث خطأ ما", fr: "Une erreur s'est produite" },

  // ─── Quizzes page (/student/quizzes) ──────────────────────────────────────
  quizzesSubtitle:   { en: "{name}'s quiz history and performance", ar: "سجل اختبارات {name} وأداؤه", fr: "Historique et résultats des quiz de {name}" },
  statAttempted:     { en: "Attempted", ar: "المحاولات", fr: "Tentés" },
  statNotYetPassed:  { en: "Not Yet Passed", ar: "لم يُجتز بعد", fr: "Pas encore réussis" },
  statAvgBestScore:  { en: "Avg Best Score", ar: "متوسط أفضل الدرجات", fr: "Meilleure note moyenne" },
  noQuizHistoryYet:  { en: "No Quiz History Yet", ar: "لا يوجد سجل اختبارات بعد", fr: "Aucun historique de quiz pour l'instant" },
  completeQuizzesDesc:{ en: "Complete quizzes inside lessons to track your performance here.", ar: "أكمل الاختبارات داخل الدروس لتتبع أدائك هنا.", fr: "Complétez les quiz dans les leçons pour suivre vos résultats ici." },
  quizHistoryHeading:{ en: "Quiz History", ar: "سجل الاختبارات", fr: "Historique des quiz" },
  bestScoreInline:   { en: "Best: {n}%", ar: "الأفضل: {n}٪", fr: "Meilleur : {n} %" },
  retryBadge:        { en: "Retry", ar: "أعد المحاولة", fr: "Réessayer" },

  // ─── Billing components (portal / cancel / reactivate / upgrade / cards) ──
  managingBilling:   { en: "Manage billing", ar: "إدارة الفواتير", fr: "Gérer la facturation" },
  openingEllipsis:   { en: "Opening...", ar: "جارٍ الفتح...", fr: "Ouverture..." },
  couldNotOpenPortal:{ en: "Could not open billing portal. Please try again.", ar: "تعذّر فتح بوابة الفواتير. حاول مرة أخرى.", fr: "Impossible d'ouvrir le portail de facturation. Veuillez réessayer." },
  reactivating:      { en: "Reactivating…", ar: "جارٍ إعادة التفعيل…", fr: "Réactivation…" },
  keepMyTrial:       { en: "Keep my trial", ar: "احتفظ بتجربتي", fr: "Garder mon essai" },
  keepMyPlan:        { en: "Keep my plan", ar: "احتفظ بخطتي", fr: "Garder mon abonnement" },
  trialKeptMsg:      { en: "Trial kept — it will convert to monthly normally.", ar: "تم الاحتفاظ بالتجربة — ستتحوّل إلى اشتراك شهري بشكل طبيعي.", fr: "Essai conservé — il passera normalement à l'abonnement mensuel." },
  reactivatedMsg:    { en: "Reactivated — your plan will renew normally.", ar: "أُعيد التفعيل — ستتجدد خطتك بشكل طبيعي.", fr: "Réactivé — votre abonnement se renouvellera normalement." },
  couldNotReactivate:{ en: "Could not reactivate subscription. Please try again.", ar: "تعذّرت إعادة تفعيل الاشتراك. حاول مرة أخرى.", fr: "Impossible de réactiver l'abonnement. Veuillez réessayer." },
  cancelling:        { en: "Cancelling…", ar: "جارٍ الإلغاء…", fr: "Annulation…" },
  cancelTrialQ:      { en: "Cancel trial?", ar: "إلغاء التجربة؟", fr: "Annuler l'essai ?" },
  cancelSubscriptionQ:{ en: "Cancel subscription?", ar: "إلغاء الاشتراك؟", fr: "Annuler l'abonnement ?" },
  keepAccessUntil:   { en: "You'll keep full access until {date}. After that, your account will lose course access.", ar: "ستحتفظ بالوصول الكامل حتى {date}. بعد ذلك، سيفقد حسابك الوصول إلى الدورة.", fr: "Vous conserverez un accès complet jusqu'au {date}. Ensuite, votre compte perdra l'accès au cours." },
  wontBeChargedTrial:{ en: " You won't be charged the monthly fee.", ar: " لن يتم تحصيل الرسوم الشهرية منك.", fr: " Vous ne serez pas facturé des frais mensuels." },
  yesCancel:         { en: "Yes, cancel", ar: "نعم، ألغِ", fr: "Oui, annuler" },
  cancelTrial:       { en: "Cancel trial", ar: "إلغاء التجربة", fr: "Annuler l'essai" },
  cancelPlan:        { en: "Cancel plan", ar: "إلغاء الخطة", fr: "Annuler l'abonnement" },
  cancelledKeepAccess:{ en: "Cancelled — you'll keep access until {date}.", ar: "تم الإلغاء — ستحتفظ بالوصول حتى {date}.", fr: "Annulé — vous conserverez l'accès jusqu'au {date}." },
  couldNotCancel:    { en: "Could not cancel subscription. Please try again.", ar: "تعذّر إلغاء الاشتراك. حاول مرة أخرى.", fr: "Impossible d'annuler l'abonnement. Veuillez réessayer." },
  upgrading:         { en: "Upgrading…", ar: "جارٍ الترقية…", fr: "Mise à niveau…" },
  monthlyPriceMo:    { en: "Monthly — ${price}/mo", ar: "شهري — {price}$/شهر", fr: "Mensuel — ${price}/mois" },
  paymentMethods:    { en: "Payment Methods", ar: "طرق الدفع", fr: "Moyens de paiement" },
  addCard:           { en: "Add card", ar: "أضف بطاقة", fr: "Ajouter une carte" },
  addNewCard:        { en: "Add a new card", ar: "أضف بطاقة جديدة", fr: "Ajouter une nouvelle carte" },
  noSavedCards:      { en: "No saved cards.", ar: "لا توجد بطاقات محفوظة.", fr: "Aucune carte enregistrée." },
  addOne:            { en: "Add one", ar: "أضف واحدة", fr: "En ajouter une" },
  loadingEllipsis:   { en: "Loading…", ar: "جارٍ التحميل…", fr: "Chargement…" },
  defaultBadge:      { en: "Default", ar: "افتراضية", fr: "Par défaut" },
  expiresOn:         { en: "Expires {date}", ar: "تنتهي في {date}", fr: "Expire le {date}" },
  expiredBadge:      { en: "Expired", ar: "منتهية", fr: "Expirée" },
  expiresSoonBadge:  { en: "Expires soon", ar: "تنتهي قريبًا", fr: "Expire bientôt" },
  settingDefault:    { en: "Setting…", ar: "جارٍ التعيين…", fr: "Définition…" },
  setAsDefault:      { en: "Set as default", ar: "اجعلها الافتراضية", fr: "Définir par défaut" },
  removeCard:        { en: "Remove card", ar: "إزالة البطاقة", fr: "Supprimer la carte" },
  savedCheckmark:    { en: "Saved", ar: "تم الحفظ", fr: "Enregistré" },
  saveCard:          { en: "Save card", ar: "احفظ البطاقة", fr: "Enregistrer la carte" },
  securedByStripe:   { en: "Secured by Stripe · Encrypted and never stored on our servers.", ar: "مؤمَّن بواسطة Stripe · مشفّر ولا يُخزَّن على خوادمنا أبدًا.", fr: "Sécurisé par Stripe · Chiffré et jamais stocké sur nos serveurs." },
  cardSetupFailed:   { en: "Card setup failed", ar: "فشل إعداد البطاقة", fr: "Échec de la configuration de la carte" },

  // ─── Welcome tour (first-run coachmark tour of /seerah) ───────────────────
  tourWelcomeTitle:   { en: "Welcome to Complete Seerah! 🌙", ar: "مرحبًا بك في Complete Seerah! 🌙", fr: "Bienvenue dans Complete Seerah ! 🌙" },
  tourWelcomeBody:    { en: "Let's take a 60-second look around your dashboard so you know exactly where everything is.", ar: "لنأخذ جولة سريعة لا تتجاوز دقيقة واحدة في لوحة التحكم لتعرف بالضبط مكان كل شيء.", fr: "Faisons un tour de 60 secondes de votre tableau de bord pour que vous sachiez exactement où tout se trouve." },
  tourHomeTitle:      { en: "Dashboard", ar: "الرئيسية", fr: "Tableau de bord" },
  tourHomeBody:       { en: "Your home base — pick up right where you left off and see your overall progress at a glance.", ar: "قاعدتك الرئيسية — استمر من حيث توقفت وشاهد تقدمك العام بنظرة واحدة.", fr: "Votre base — reprenez exactement où vous vous êtes arrêté et voyez votre progression globale d'un coup d'œil." },
  tourLessonsTitle:   { en: "Lessons", ar: "الدروس", fr: "Leçons" },
  tourLessonsBody:    { en: "All 100 parts of the Seerah, organized in order across 8 stages — from pre-Islamic Arabia to the Prophet\u2019s \ufdfa final years.", ar: "جميع الأجزاء المئة من السيرة النبوية، منظمة بالترتيب عبر ٨ مراحل — من الجزيرة العربية قبل الإسلام حتى السنوات الأخيرة من حياة النبي ﷺ.", fr: "Les 100 parties de la Sîra, organisées dans l'ordre en 8 étapes — de l'Arabie préislamique aux dernières années du Prophète \ufdfa." },
  tourResourcesTitle: { en: "Resources", ar: "الموارد", fr: "Ressources" },
  tourResourcesBody:  { en: "Videos, audio, briefings, slides, flashcards, and quizzes for every part — all in one place.", ar: "فيديوهات وتسجيلات صوتية وملخصات وشرائح وبطاقات تعليمية واختبارات لكل جزء — كلها في مكان واحد.", fr: "Vidéos, audio, briefings, diapositives, flashcards et quiz pour chaque partie — le tout au même endroit." },
  tourReferenceTitle: { en: "Reference", ar: "المرجع", fr: "Référence" },
  tourReferenceBody:  { en: "A searchable library of key people, places, battles, tribes, and terms — great for quick lookups.", ar: "مكتبة قابلة للبحث تضم أهم الشخصيات والأماكن والمعارك والقبائل والمصطلحات — مثالية للبحث السريع.", fr: "Une bibliothèque consultable de personnages, lieux, batailles, tribus et termes clés — idéale pour les recherches rapides." },
  tourProgressTitle:  { en: "Progress", ar: "التقدم", fr: "Progression" },
  tourProgressBody:   { en: "Track how far you've come, your quiz scores, and what's coming up next.", ar: "تابع مدى تقدمك ودرجات اختباراتك وما هو قادم بعد ذلك.", fr: "Suivez votre avancement, vos scores aux quiz et ce qui vous attend ensuite." },
  tourOutroTitle:     { en: "You're all set!", ar: "أنت جاهز الآن!", fr: "Vous êtes prêt !" },
  tourOutroBody:      { en: "That's the whole dashboard. Enjoy the journey through the Seerah of the Prophet \ufdfa.", ar: "هذه هي لوحة التحكم بالكامل. نتمنى لك رحلة ممتعة عبر سيرة النبي ﷺ.", fr: "Voilà tout le tableau de bord. Profitez du voyage à travers la Sîra du Prophète \ufdfa." },
  tourStepOfN:        { en: "Step {n} of {m}", ar: "الخطوة {n} من {m}", fr: "Étape {n} sur {m}" },
  tourSkip:           { en: "Skip", ar: "تخطّ", fr: "Passer" },
  tourBack:           { en: "Back", ar: "رجوع", fr: "Retour" },
  tourNext:           { en: "Next", ar: "التالي", fr: "Suivant" },
  tourStart:          { en: "Start tour", ar: "ابدأ الجولة", fr: "Démarrer la visite" },
  tourGetStarted:     { en: "Get started", ar: "ابدأ الآن", fr: "Commencer" },

  // ─── Past-due / email banners ─────────────────────────────────────────────
  pastDueBanner:     { en: "⚠️ Your last payment failed. Fix your card to keep access — your progress is safe.", ar: "⚠️ فشل آخر دفع. أصلح بطاقتك للحفاظ على وصولك — تقدمك محفوظ.", fr: "⚠️ Votre dernier paiement a échoué. Mettez à jour votre carte pour conserver l'accès — votre progression est en sécurité." },
  updatePayment:     { en: "Update payment →", ar: "تحديث الدفع →", fr: "Mettre à jour le paiement →" },
  verifyEmailBanner: { en: "Please verify your email address to unlock all features.", ar: "يرجى التحقق من بريدك الإلكتروني لفتح جميع الميزات.", fr: "Veuillez vérifier votre adresse e-mail pour débloquer toutes les fonctionnalités." },
  resendEmail:       { en: "Resend email", ar: "أعد الإرسال", fr: "Renvoyer l'e-mail" },
  dismiss:           { en: "Dismiss", ar: "إغلاق", fr: "Fermer" },
};

export type UiStringKey = keyof typeof S;

/** Returns the UI string for the given lang. */
export function t(lang: CourseLang, key: UiStringKey): string {
  return S[key][lang];
}

/**
 * Returns a UI string with `{placeholder}` tokens replaced.
 * e.g. tf(lang, "stageNofM", { n: 3, m: 8 }) → "Stage 3 of 8" / "المرحلة 3 من 8"
 */
export function tf(lang: CourseLang, key: UiStringKey, vars: Record<string, string | number>): string {
  let result = S[key][lang];
  for (const [k, v] of Object.entries(vars)) {
    result = result.replace(`{${k}}`, String(v));
  }
  return result;
}

/** ERA descriptions when Arabic is selected */
export const ERA_DESCRIPTIONS_AR: Record<string, string> = {
  "Pre-Islamic Arabia":    "اكتشف العالم الذي بُعث فيه النبي ﷺ ليغيّره",
  "Birth & Early Life":   "من نسبه الشريف إلى أخلاقه قبل النبوة",
  "Beginning of Revelation": "أول الآيات، والدعوة إلى الإسلام، والمؤمنون الأوائل",
  "Makkah — Persecution": "كيف صبر المسلمون الأوائل على الأذى والرفض والتضحية",
  "The Hijrah":           "الهجرة التي غيّرت مجرى التاريخ وأسست مجتمعًا جديدًا",
  "Madinah Period":       "بناء أول مجتمع إسلامي وتأسيس الأمة",
  "Major Campaigns":      "الغزوات التي دافعت عن الإسلام وشكّلت توسعه",
  "Final Years & Legacy": "فتح مكة وحجة الوداع ووفاة النبي ﷺ",
};

/** ERA descriptions when French is selected */
export const ERA_DESCRIPTIONS_FR: Record<string, string> = {
  "Pre-Islamic Arabia": "Comprendre le monde que le Prophète ﷺ a été envoyé transformer",
  "Birth & Early Life": "De sa noble lignée à son caractère avant la prophétie",
  "Beginning of Revelation": "Les premiers signes, l'appel à l'islam et les premiers croyants",
  "Makkah — Persecution": "Comment les premiers musulmans ont enduré pression, rejet et sacrifice",
  "The Hijrah": "La migration qui a changé l'histoire et fondé une nouvelle société",
  "Madinah Period": "Construction de la première communauté islamique et établissement de l'Oumma",
  "Major Campaigns": "Les batailles qui ont défendu l'islam et façonné son expansion",
  "Final Years & Legacy": "La conquête de La Mecque, le Sermon d'adieu et le décès du Prophète ﷺ",
};
