import type { CourseLang } from "./course-lang";

/**
 * Shared UI string dictionary for the student course shell.
 * Usage: t(lang, "key") or tf(lang, "key", { n: 5 }) for interpolated strings.
 */

const S = {
  // ─── Dashboard tabs ──────────────────────────────────────────────────────────
  tabDashboard:      { en: "Dashboard",   ar: "الرئيسية"     },
  tabHome:           { en: "Home",        ar: "الرئيسية"     },
  tabLessons:        { en: "Lessons",     ar: "الدروس"       },
  tabResources:      { en: "Resources",   ar: "الموارد"      },
  tabMedia:          { en: "Media",       ar: "الوسائط"      },
  tabReference:      { en: "Reference",   ar: "المرجع"       },
  tabRef:            { en: "Ref",         ar: "مرجع"         },
  tabProgress:       { en: "Progress",    ar: "التقدم"       },
  tabStats:          { en: "Stats",       ar: "إحصائيات"    },
  tabAcct:           { en: "Acct",        ar: "الحساب"       },
  openAccountMenu:   { en: "Open account menu",  ar: "فتح قائمة الحساب" },
  courseSections:    { en: "Course sections",    ar: "أقسام الدورة"     },

  // ─── Home content ─────────────────────────────────────────────────────────
  welcomeBack:       { en: "Welcome back",                   ar: "مرحبًا بعودتك"              },
  part1Free:         { en: "Part 1 is free — begin the Seerah today.", ar: "الجزء الأول مجاني — ابدأ السيرة النبوية اليوم." },
  freeStartHere:     { en: "Free — Start Here",              ar: "مجاني — ابدأ من هنا"         },
  startHere:         { en: "Start here",                     ar: "ابدأ من هنا"                 },
  continueLearning:  { en: "Continue learning",              ar: "استمر في التعلم"             },
  partN:             { en: "Part {n}",                       ar: "الجزء {n}"                   },
  stageNofM:         { en: "Stage {n} of {m}",               ar: "المرحلة {n} من {m}"          },
  minRead:           { en: "15–20 min",                      ar: "١٥–٢٠ دقيقة"                },
  bestStartingPoint: { en: "Best starting point",            ar: "أفضل نقطة بداية"            },
  lessonProgress:    { en: "Lesson progress",                ar: "تقدم الدرس"                  },
  startPartN:        { en: "Start Part {n}",                 ar: "ابدأ الجزء {n}"              },
  continuLesson:     { en: "Continue Lesson",                ar: "استمر في الدرس"              },
  viewRoadmap:       { en: "View Roadmap",                   ar: "عرض خريطة الدورة"           },
  howToUseLesson:    { en: "How to use each lesson",         ar: "كيف تستخدم كل درس"          },
  allFormatsRetention:{ en: "All four formats together for best retention", ar: "الجمع بين الأشكال الأربعة لأفضل نتيجة" },
  watchTheVideo:     { en: "Watch the video",                ar: "شاهد الفيديو"                },
  readTheBriefing:   { en: "Read the briefing",              ar: "اقرأ الملخص"                 },
  reviewFlashcards:  { en: "Review flashcards",              ar: "راجع البطاقات التعليمية"     },
  takeTheQuiz:       { en: "Take the quiz",                  ar: "أجرِ الاختبار"               },
  unlockAllN:        { en: "Unlock All {n} Parts",           ar: "افتح جميع الـ {n} جزءًا"    },
  unlockDesc:        { en: "Get lifetime access to the full Seerah course — videos, reading notes, flashcards, and quizzes for every part.", ar: "احصل على وصول مدى الحياة إلى دورة السيرة النبوية الكاملة — فيديوهات وملخصات وبطاقات تعليمية واختبارات لكل جزء." },
  viewPlans:         { en: "View Plans",                     ar: "عرض الخطط"                  },
  completedStat:     { en: "Completed",                      ar: "مكتملة"                      },
  partsFullyCompleted:{ en: "Parts fully completed",         ar: "أجزاء مكتملة بالكامل"       },
  requiresQuiz:      { en: "Requires passing the quiz (80%+)", ar: "يتطلب اجتياز الاختبار (٨٠٪+)" },
  currentStage:      { en: "Current Stage",                  ar: "المرحلة الحالية"             },
  nextLesson:        { en: "Next Lesson",                    ar: "الدرس التالي"                },
  startNow:          { en: "Start now",                      ar: "ابدأ الآن"                   },
  continue:          { en: "Continue",                       ar: "استمر"                       },
  courseRoadmap:     { en: "Course Roadmap",                 ar: "خريطة الدورة"               },
  seerahInStages:    { en: "The Seerah in {n} stages — from pre-Islamic Arabia to the Prophet\u2019s \ufdfa final years. Each part unlocks after you complete the previous lesson\u2019s quiz. Follow the order for the full picture.", ar: "السيرة النبوية في {n} مراحل — من الجزيرة العربية قبل الإسلام حتى السنوات الأخيرة من حياة النبي ﷺ." },
  currentStageLabel: { en: "▸ Current",                     ar: "▸ الحالية"                   },
  stageN:            { en: "Stage {n}",                      ar: "المرحلة {n}"                 },
  review:            { en: "Review",                         ar: "راجع"                        },
  start:             { en: "Start",                          ar: "ابدأ"                        },
  quickAccessTools:  { en: "Quick Access to Course Tools",   ar: "الوصول السريع إلى أدوات الدورة" },
  everyPartIncludes: { en: "Every part includes all of these formats. Use them in any order.", ar: "كل جزء يشمل هذه الأشكال جميعًا. استخدمها بأي ترتيب." },
  watchLessons:      { en: "Watch Lessons",                  ar: "شاهد الدروس"                },
  readBriefings:     { en: "Read Briefings",                 ar: "اقرأ الملخصات"              },
  listenOnTheGo:     { en: "Listen on the Go",               ar: "استمع أثناء التنقل"         },
  slides:            { en: "Slides",                         ar: "الشرائح"                     },
  infographics:      { en: "Infographics",                   ar: "الرسوم المعلوماتية"         },
  mindMaps:          { en: "Mind Maps",                      ar: "الخرائط الذهنية"            },
  flashcards:        { en: "Flashcards",                     ar: "البطاقات التعليمية"         },
  quizzes:           { en: "Quizzes",                        ar: "الاختبارات"                  },
  needHelp:          { en: "Need help getting started?",     ar: "هل تحتاج إلى مساعدة؟"       },
  helpDesc:          { en: "If something does not load, or you are unsure where to begin, contact support.", ar: "إذا لم يتم تحميل شيء، أو لم تعرف من أين تبدأ، تواصل مع الدعم." },
  contactSupport:    { en: "Contact Support",                ar: "تواصل مع الدعم"             },

  // ─── Progress page ────────────────────────────────────────────────────────
  yourProgress:      { en: "Your Progress",                  ar: "تقدمك"                       },
  journeyDesc:       { en: "Your journey through the Complete Seerah course.", ar: "رحلتك عبر دورة السيرة النبوية الكاملة." },
  startLearning:     { en: "Start Learning",                 ar: "ابدأ التعلم"                 },
  beginPart1:        { en: "Begin Part 1 of the Seerah",     ar: "ابدأ الجزء الأول من السيرة"  },
  continueLearningBtn:{ en: "Continue Learning",             ar: "استمر في التعلم"             },
  progressStat:      { en: "Progress",                       ar: "التقدم"                      },
  notStartedYet:     { en: "Not started yet",                ar: "لم تبدأ بعد"                 },
  ofFullSeerah:      { en: "of the full Seerah",             ar: "من السيرة الكاملة"           },
  avgQuizScore:      { en: "Avg Quiz Score",                 ar: "متوسط الاختبارات"           },
  attempts1:         { en: "{n} attempt",                    ar: "{n} محاولة"                  },
  attemptsN:         { en: "{n} attempts",                   ar: "{n} محاولات"                 },
  noQuizzesYet:      { en: "No quizzes attempted yet",       ar: "لم يُحاول في أي اختبار بعد" },
  howPartsCompleted: { en: "How parts are counted as completed", ar: "كيف تُحسب الأجزاء المكتملة" },
  passQuizWith80:    { en: "Pass the Quiz with 80% or higher", ar: "اجتاز الاختبار بنسبة ٨٠٪ فأكثر" },
  stageProgress:     { en: "Stage Progress",                 ar: "تقدم المراحل"               },
  nStages:           { en: "{n} stages",                     ar: "{n} مراحل"                   },
  recentlyOpened:    { en: "Recently Opened",                ar: "مفتوحة مؤخرًا"              },
  noActivityYet:     { en: "No activity yet",                ar: "لا يوجد نشاط بعد"           },
  startPart1Prompt:  { en: "Start Part 1 and your recent lessons will appear here.", ar: "ابدأ الجزء الأول وستظهر دروسك الأخيرة هنا." },
  startPart1:        { en: "Start Part 1",                   ar: "ابدأ الجزء الأول"           },
  nPartsCompleted:   { en: "{n} part{s} completed",          ar: "{n} جزء مكتمل"              },
  viewLink:          { en: "View",                           ar: "عرض"                         },
  inProgress:        { en: "In Progress",                    ar: "جاري"                        },

  // ─── Lessons path ─────────────────────────────────────────────────────────
  lessonsHeader:     { en: "Lessons",                        ar: "الدروس"                      },
  lessonsSubheader:  { en: "The complete Seerah of the Prophet \ufdfa in 100 parts, arranged chronologically.", ar: "السيرة النبوية الكاملة في ١٠٠ جزء، مرتبة تاريخيًا." },
  locked:            { en: "Locked",                         ar: "مقفل"                        },
  assetVideo:        { en: "Video",                          ar: "الفيديو"                     },
  assetBriefing:     { en: "Briefing",                       ar: "الملخص"                      },
  assetSlides:       { en: "Slides",                         ar: "الشرائح"                     },
  assetAudio:        { en: "Audio",                          ar: "الصوت"                       },
  assetMindmap:      { en: "Mind Map",                       ar: "الخريطة الذهنية"            },
  assetFlashcards:   { en: "Flashcards",                     ar: "بطاقات تعليمية"             },
  assetQuiz:         { en: "Quiz",                           ar: "الاختبار"                    },
  nParts:            { en: "{n} {part}",                     ar: "{n} جزء"                     },

  // ─── Resources hub (course-resources-content) ─────────────────────────────
  yourResources:     { en: "Your Resources",                 ar: "مواردك"                      },
  videoLessons:      { en: "Video Lessons",                  ar: "دروس الفيديو"               },
  videoLessonsDesc:  { en: "Watch all 100 guided video lessons", ar: "شاهد جميع الـ ١٠٠ درس" },
  listenGoDesc:      { en: "Audio version of every lesson",  ar: "النسخة الصوتية لكل درس"     },
  briefings:         { en: "Briefings",                      ar: "الملخصات"                    },
  briefingsDesc:     { en: "Read briefings for each part",   ar: "اقرأ ملخص كل جزء"           },
  slidesDesc:        { en: "3 formats: Presented, Detailed, Facts", ar: "٣ أشكال: مقدَّمة، مفصَّلة، معلومات" },
  infographicsDesc:  { en: "3 formats: Concise, Standard, Bento Grid", ar: "٣ أشكال: موجزة، قياسية، شبكية" },
  mindMapsDesc:      { en: "Visual maps connecting people and events", ar: "خرائط مرئية تربط الأشخاص والأحداث" },
  flashcardsDesc:    { en: "Easy, Medium, and Hard flashcard sets", ar: "مجموعات سهلة ومتوسطة وصعبة" },
  quizzesDesc:       { en: "Test your knowledge for each part", ar: "اختبر معلوماتك في كل جزء" },
  reports:           { en: "Reports",                        ar: "التقارير"                    },
  reportsDesc:       { en: "Comprehensive reports for each lesson", ar: "تقارير شاملة لكل درس" },
  studyGuides:       { en: "Study Guides",                   ar: "أدلة الدراسة"               },
  studyGuidesDesc:   { en: "Detailed study guides for review", ar: "أدلة دراسة تفصيلية للمراجعة" },
  facts:             { en: "Facts",                          ar: "المعلومات"                   },
  factsDesc:         { en: "Quick reference facts for each part", ar: "معلومات مرجعية سريعة لكل جزء" },

  // ─── Reference library ────────────────────────────────────────────────────
  referenceLibrary:  { en: "Reference Library",              ar: "مكتبة المراجع"              },
  seerahReferenceLib:{ en: "Seerah Reference Library",       ar: "مكتبة مراجع السيرة النبوية" },
  referenceLibDesc:  { en: "Extra Seerah reference guides, timelines, people, places, and historical notes to help you understand the life of the Prophet \ufdfa more clearly.", ar: "مراجع إضافية، تسلسل زمني، شخصيات، أماكن وملاحظات تاريخية لفهم أعمق لسيرة النبي ﷺ." },
  backToRefLib:      { en: "Back to Reference Library",      ar: "العودة إلى مكتبة المراجع"   },
  moreSectionsSoon:  { en: "More reference sections coming soon. Use these resources alongside your lessons to deepen your understanding of the Seerah.", ar: "مزيد من أقسام المراجع قريبًا. استخدم هذه الموارد مع دروسك لتعميق فهمك للسيرة النبوية." },
  viewCard:          { en: "View {title}",                   ar: "عرض {title}"                },

  // Reference card titles + descriptions
  refFamilyTitle:    { en: "Family & Household",             ar: "الأسرة والبيت"              },
  refFamilyDesc:     { en: "A clear guide to the wives, children, and household of the Prophet \ufdfa, with simple tables and historical notes.", ar: "دليل واضح لزوجات النبي ﷺ وأبنائه وأسرته، مع جداول بسيطة وملاحظات تاريخية." },
  refTimelineTitle:  { en: "Timeline of the Seerah",         ar: "التسلسل الزمني للسيرة"      },
  refTimelineDesc:   { en: "A chronological timeline of major events in the life of the Prophet \ufdfa.", ar: "تسلسل زمني للأحداث الرئيسية في حياة النبي ﷺ." },
  refKeyPeopleTitle: { en: "Key People in the Seerah",       ar: "أبرز شخصيات السيرة"         },
  refKeyPeopleDesc:  { en: "Companions, leaders, and figures whose roles shaped the early Muslim community.", ar: "الصحابة والقادة والشخصيات التي أثّرت في تشكيل المجتمع الإسلامي الأول." },
  refTribesTitle:    { en: "Tribes and Lineage",             ar: "القبائل والنسب"             },
  refTribesDesc:     { en: "The major Arab tribes, their relationships, and the Prophet\u2019s \ufdfa lineage traced back.", ar: "أبرز القبائل العربية وعلاقاتها، ونسب النبي ﷺ." },
  refPlacesTitle:    { en: "Places and Maps",                ar: "الأماكن والخرائط"           },
  refPlacesDesc:     { en: "A reference to the key cities, routes, and locations mentioned in the Seerah.", ar: "مرجع لأهم المدن والطرق والمواقع المذكورة في السيرة." },
  refBattlesTitle:   { en: "Battles and Expeditions",        ar: "الغزوات والسرايا"           },
  refBattlesDesc:    { en: "A clear reference to the major battles, campaigns, and expeditions of the Prophet \ufdfa.", ar: "مرجع واضح لأهم المعارك والحملات والغزوات." },
  refMiraclesTitle:  { en: "Miracles and Signs",             ar: "المعجزات والآيات"           },
  refMiraclesDesc:   { en: "Verified narrations of miracles and signs granted to the Prophet \ufdfa.", ar: "روايات موثقة من معجزات وآيات النبي ﷺ." },
  refTermsTitle:     { en: "Important Terms",                ar: "المصطلحات المهمة"           },
  refTermsDesc:      { en: "A glossary of Arabic and historical terms used throughout the Seerah.", ar: "مسرد للمصطلحات العربية والتاريخية المستخدمة في السيرة." },

  // ─── Resources library tabs ───────────────────────────────────────────────
  course:            { en: "Course",                         ar: "الدورة"                      },
  resources:         { en: "Resources",                      ar: "الموارد"                     },
  breadcrumbLabel:   { en: "Breadcrumb",                     ar: "مسار التنقل"                },
  resourceLibrary:   { en: "Resource Library",               ar: "مكتبة الموارد"              },
  resourceLibSubtitle:{ en: "All learning materials across the complete Seerah Masterclass", ar: "جميع المواد التعليمية لدورة السيرة النبوية الكاملة" },
  videos:            { en: "Videos",                         ar: "الفيديوهات"                  },
  audio:             { en: "Audio",                          ar: "الصوت"                       },
  mindmapsTab:       { en: "Mindmaps",                       ar: "الخرائط الذهنية"            },
  resourceTypes:     { en: "Resource types",                 ar: "أنواع الموارد"              },

  // ─── Resource filter bar ──────────────────────────────────────────────────
  searchLessons:     { en: "Search lessons...",              ar: "ابحث عن الدروس..."           },
  clearSearch:       { en: "Clear search",                   ar: "مسح البحث"                  },
  toggleFilters:     { en: "Toggle filters",                 ar: "تبديل الفلاتر"             },
  stageEra:          { en: "Stage / Era",                    ar: "المرحلة / العصر"            },
  allStages:         { en: "All Stages",                     ar: "جميع المراحل"               },
  status:            { en: "Status",                         ar: "الحالة"                      },
  all:               { en: "All",                            ar: "الكل"                        },
  completedFilter:   { en: "Completed",                      ar: "المكتملة"                    },
  inProgressFilter:  { en: "In Progress",                    ar: "جارية"                       },
  notStarted:        { en: "Not Started",                    ar: "لم تُبدأ"                    },
  clearFilters:      { en: "Clear filters",                  ar: "مسح الفلاتر"               },

  // ─── Video resource content ───────────────────────────────────────────────
  videoLessonsH1:    { en: "Video Lessons",                  ar: "دروس الفيديو"               },
  allNLessons:       { en: "All {n} guided lessons from the Seerah Masterclass", ar: "جميع الـ {n} درسًا الإرشادية" },
  nOfMCompleted:     { en: "{n} of {m} video lessons completed · continue building your Seerah timeline", ar: "{n} من {m} درسًا مكتملًا · واصل بناء مسيرتك" },
  statTotal:         { en: "Total",                          ar: "المجموع"                     },
  statCompleted:     { en: "Completed",                      ar: "مكتملة"                      },
  statInProgress:    { en: "In Progress",                    ar: "جارية"                       },
  statNotStarted:    { en: "Not Started",                    ar: "لم تُبدأ"                    },
  continueWatching:  { en: "Continue Watching",              ar: "استمر في المشاهدة"          },
  nPctWatched:       { en: "{n}% watched",                   ar: "{n}٪ تمت مشاهدته"           },
  resume:            { en: "Resume",                         ar: "استمر"                       },
  closeVideo:        { en: "Close video",                    ar: "إغلاق الفيديو"              },
  done:              { en: "Done",                           ar: "مكتمل"                       },
  partLabel:         { en: "Part {n}",                       ar: "الجزء {n}"                   },
  resumePartAriaLabel: { en: "Resume Part {n}: {title}",     ar: "استمر في الجزء {n}: {title}" },

  // ─── Audio resource content ───────────────────────────────────────────────
  allNAudio:         { en: "All {n} audio lessons from the Seerah Masterclass", ar: "جميع الـ {n} درسًا الصوتية" },
  nowPlaying:        { en: "Now Playing",                    ar: "يُشغَّل الآن"               },
  audioNotAvail:     { en: "Audio not available for this lesson", ar: "الصوت غير متاح لهذا الدرس" },
  listenNow:         { en: "Listen",                         ar: "استمع"                       },
  closeAudio:        { en: "Close audio player",             ar: "إغلاق مشغل الصوت"          },
  previousTrack:     { en: "Previous track",                 ar: "المقطع السابق"              },
  nextTrack:         { en: "Next track",                     ar: "المقطع التالي"              },
  mute:              { en: "Mute",                           ar: "كتم الصوت"                  },
  unmute:            { en: "Unmute",                         ar: "رفع الصوت"                  },

  // ─── Text / quiz / simple resource content ────────────────────────────────
  nOfMRead:          { en: "{n} of {m} read",                ar: "{n} من {m} مقروء"           },
  nOfMViewed:        { en: "{n} of {m} viewed",              ar: "{n} من {m} تمت مشاهدته"     },
  nOfMStudied:       { en: "{n} of {m} studied",             ar: "{n} من {m} تمت دراسته"      },
  readNow:           { en: "Read",                           ar: "اقرأ"                        },
  viewNow:           { en: "View",                           ar: "عرض"                         },
  studyNow:          { en: "Study",                          ar: "ادرس"                        },
  closeModal:        { en: "Close",                          ar: "إغلاق"                       },
  statRead:          { en: "Read",                           ar: "مقروء"                       },
  statViewed:        { en: "Viewed",                         ar: "تمت مشاهدته"                 },
  statStudied:       { en: "Studied",                        ar: "تمت دراسته"                  },
  statUnread:        { en: "Unread",                         ar: "غير مقروء"                   },
  statNotViewed:     { en: "Not Viewed",                     ar: "لم تُشاهَد"                  },
  statNotStudied:    { en: "Not Studied",                    ar: "لم تُدرَس"                   },
  noSlidesAvailable: { en: "No slides available",            ar: "لا توجد شرائح متاحة"         },
  resourceNotAvailable: { en: "Resource not available",      ar: "المورد غير متاح"             },
  noFlashcardsAvailable: { en: "No flashcards available",    ar: "لا توجد بطاقات تعليمية متاحة" },
  resetZoom:         { en: "Reset Zoom",                     ar: "إعادة ضبط التكبير"          },
  scrollToZoomDragToPan: { en: "Scroll to zoom, drag to pan", ar: "مرّر للتكبير، واسحب للتحريك" },
  clickToExitFullscreen: { en: "Click to exit fullscreen",   ar: "اضغط للخروج من وضع ملء الشاشة" },
  clickToViewFullscreen: { en: "Click to view fullscreen",   ar: "اضغط لعرض ملء الشاشة"       },

  // ─── Quiz resource content ────────────────────────────────────────────────
  nOfMPassed:        { en: "{n} of {m} passed",              ar: "{n} من {m} اجتازها"         },
  avgScore:          { en: "Avg Score",                      ar: "متوسط الدرجات"              },
  totalAttempts:     { en: "Total Attempts",                 ar: "إجمالي المحاولات"           },
  passed:            { en: "Passed",                         ar: "اجتاز"                       },
  failed:            { en: "Failed",                         ar: "لم يجتز"                     },
  notAttempted:      { en: "Not Attempted",                  ar: "لم يُحاول"                   },
  takeQuiz:          { en: "Take Quiz",                      ar: "أجرِ الاختبار"               },
  retakeQuiz:        { en: "Retake",                         ar: "أعد الاختبار"               },
  closeQuiz:         { en: "Close quiz",                     ar: "إغلاق الاختبار"             },

  // ─── Change password form ─────────────────────────────────────────────────
  changePassword:    { en: "Change Password",             ar: "تغيير كلمة المرور"           },
  currentPassword:   { en: "Current password",            ar: "كلمة المرور الحالية"         },
  enterCurrentPassword:{ en: "Enter current password",    ar: "أدخل كلمة المرور الحالية"    },
  newPassword:       { en: "New password",                ar: "كلمة المرور الجديدة"         },
  atLeast8Chars:     { en: "At least 8 characters",        ar: "٨ أحرف على الأقل"            },
  confirmNewPassword:{ en: "Confirm new password",         ar: "تأكيد كلمة المرور الجديدة"   },
  reenterNewPassword:{ en: "Re-enter new password",        ar: "أعد إدخال كلمة المرور الجديدة" },
  passwordsMatch:    { en: "Passwords match",              ar: "كلمتا المرور متطابقتان"      },
  passwordsDontMatch:{ en: "Passwords don't match",        ar: "كلمتا المرور غير متطابقتين"  },
  updated:           { en: "Updated",                      ar: "تم التحديث"                  },
  saving:            { en: "Saving…",                      ar: "جارٍ الحفظ…"                 },
  updatePassword:    { en: "Update Password",              ar: "تحديث كلمة المرور"           },
  cancel:            { en: "Cancel",                       ar: "إلغاء"                       },
  somethingWentWrong:{ en: "Something went wrong",         ar: "حدث خطأ ما"                  },

  // ─── Quizzes page (/student/quizzes) ──────────────────────────────────────
  quizzesSubtitle:   { en: "{name}'s quiz history and performance", ar: "سجل اختبارات {name} وأداؤه" },
  statAttempted:     { en: "Attempted",                  ar: "المحاولات"                   },
  statNotYetPassed:  { en: "Not Yet Passed",              ar: "لم يُجتز بعد"                },
  statAvgBestScore:  { en: "Avg Best Score",              ar: "متوسط أفضل الدرجات"          },
  noQuizHistoryYet:  { en: "No Quiz History Yet",         ar: "لا يوجد سجل اختبارات بعد"    },
  completeQuizzesDesc:{ en: "Complete quizzes inside lessons to track your performance here.", ar: "أكمل الاختبارات داخل الدروس لتتبع أدائك هنا." },
  quizHistoryHeading:{ en: "Quiz History",                ar: "سجل الاختبارات"              },
  bestScoreInline:   { en: "Best: {n}%",                  ar: "الأفضل: {n}٪"                },
  retryBadge:        { en: "Retry",                       ar: "أعد المحاولة"                },

  // ─── Billing components (portal / cancel / reactivate / upgrade / cards) ──
  managingBilling:   { en: "Manage billing",                ar: "إدارة الفواتير"              },
  openingEllipsis:   { en: "Opening...",                    ar: "جارٍ الفتح..."               },
  couldNotOpenPortal:{ en: "Could not open billing portal. Please try again.", ar: "تعذّر فتح بوابة الفواتير. حاول مرة أخرى." },
  reactivating:      { en: "Reactivating…",                 ar: "جارٍ إعادة التفعيل…"          },
  keepMyTrial:       { en: "Keep my trial",                 ar: "احتفظ بتجربتي"               },
  keepMyPlan:        { en: "Keep my plan",                  ar: "احتفظ بخطتي"                 },
  trialKeptMsg:      { en: "Trial kept — it will convert to monthly normally.", ar: "تم الاحتفاظ بالتجربة — ستتحوّل إلى اشتراك شهري بشكل طبيعي." },
  reactivatedMsg:    { en: "Reactivated — your plan will renew normally.", ar: "أُعيد التفعيل — ستتجدد خطتك بشكل طبيعي." },
  couldNotReactivate:{ en: "Could not reactivate subscription. Please try again.", ar: "تعذّرت إعادة تفعيل الاشتراك. حاول مرة أخرى." },
  cancelling:        { en: "Cancelling…",                   ar: "جارٍ الإلغاء…"                },
  cancelTrialQ:      { en: "Cancel trial?",                 ar: "إلغاء التجربة؟"              },
  cancelSubscriptionQ:{ en: "Cancel subscription?",         ar: "إلغاء الاشتراك؟"             },
  keepAccessUntil:   { en: "You'll keep full access until {date}. After that, your account will lose course access.", ar: "ستحتفظ بالوصول الكامل حتى {date}. بعد ذلك، سيفقد حسابك الوصول إلى الدورة." },
  wontBeChargedTrial:{ en: " You won't be charged the monthly fee.", ar: " لن يتم تحصيل الرسوم الشهرية منك." },
  yesCancel:         { en: "Yes, cancel",                   ar: "نعم، ألغِ"                    },
  cancelTrial:       { en: "Cancel trial",                  ar: "إلغاء التجربة"               },
  cancelPlan:        { en: "Cancel plan",                   ar: "إلغاء الخطة"                 },
  cancelledKeepAccess:{ en: "Cancelled — you'll keep access until {date}.", ar: "تم الإلغاء — ستحتفظ بالوصول حتى {date}." },
  couldNotCancel:    { en: "Could not cancel subscription. Please try again.", ar: "تعذّر إلغاء الاشتراك. حاول مرة أخرى." },
  upgrading:         { en: "Upgrading…",                    ar: "جارٍ الترقية…"                },
  monthlyPriceMo:    { en: "Monthly — ${price}/mo",         ar: "شهري — {price}$/شهر"          },
  paymentMethods:    { en: "Payment Methods",                ar: "طرق الدفع"                   },
  addCard:           { en: "Add card",                      ar: "أضف بطاقة"                   },
  addNewCard:        { en: "Add a new card",                ar: "أضف بطاقة جديدة"             },
  noSavedCards:      { en: "No saved cards.",                ar: "لا توجد بطاقات محفوظة."       },
  addOne:            { en: "Add one",                        ar: "أضف واحدة"                   },
  loadingEllipsis:   { en: "Loading…",                       ar: "جارٍ التحميل…"                },
  defaultBadge:      { en: "Default",                        ar: "افتراضية"                    },
  expiresOn:         { en: "Expires {date}",                 ar: "تنتهي في {date}"             },
  expiredBadge:      { en: "Expired",                        ar: "منتهية"                       },
  expiresSoonBadge:  { en: "Expires soon",                   ar: "تنتهي قريبًا"                 },
  settingDefault:    { en: "Setting…",                       ar: "جارٍ التعيين…"                },
  setAsDefault:      { en: "Set as default",                 ar: "اجعلها الافتراضية"           },
  removeCard:        { en: "Remove card",                    ar: "إزالة البطاقة"               },
  savedCheckmark:    { en: "Saved",                          ar: "تم الحفظ"                     },
  saveCard:          { en: "Save card",                      ar: "احفظ البطاقة"                },
  securedByStripe:   { en: "Secured by Stripe · Encrypted and never stored on our servers.", ar: "مؤمَّن بواسطة Stripe · مشفّر ولا يُخزَّن على خوادمنا أبدًا." },
  cardSetupFailed:   { en: "Card setup failed",               ar: "فشل إعداد البطاقة"           },

  // ─── Welcome tour (first-run coachmark tour of /seerah) ───────────────────
  tourWelcomeTitle:   { en: "Welcome to Complete Seerah! 🌙", ar: "مرحبًا بك في Complete Seerah! 🌙" },
  tourWelcomeBody:    { en: "Let's take a 60-second look around your dashboard so you know exactly where everything is.", ar: "لنأخذ جولة سريعة لا تتجاوز دقيقة واحدة في لوحة التحكم لتعرف بالضبط مكان كل شيء." },
  tourHomeTitle:      { en: "Dashboard",   ar: "الرئيسية" },
  tourHomeBody:       { en: "Your home base — pick up right where you left off and see your overall progress at a glance.", ar: "قاعدتك الرئيسية — استمر من حيث توقفت وشاهد تقدمك العام بنظرة واحدة." },
  tourLessonsTitle:   { en: "Lessons",     ar: "الدروس" },
  tourLessonsBody:    { en: "All 100 parts of the Seerah, organized in order across 8 stages — from pre-Islamic Arabia to the Prophet\u2019s \ufdfa final years.", ar: "جميع الأجزاء المئة من السيرة النبوية، منظمة بالترتيب عبر ٨ مراحل — من الجزيرة العربية قبل الإسلام حتى السنوات الأخيرة من حياة النبي ﷺ." },
  tourResourcesTitle: { en: "Resources",   ar: "الموارد" },
  tourResourcesBody:  { en: "Videos, audio, briefings, slides, flashcards, and quizzes for every part — all in one place.", ar: "فيديوهات وتسجيلات صوتية وملخصات وشرائح وبطاقات تعليمية واختبارات لكل جزء — كلها في مكان واحد." },
  tourReferenceTitle: { en: "Reference",   ar: "المرجع" },
  tourReferenceBody:  { en: "A searchable library of key people, places, battles, tribes, and terms — great for quick lookups.", ar: "مكتبة قابلة للبحث تضم أهم الشخصيات والأماكن والمعارك والقبائل والمصطلحات — مثالية للبحث السريع." },
  tourProgressTitle:  { en: "Progress",    ar: "التقدم" },
  tourProgressBody:   { en: "Track how far you've come, your quiz scores, and what's coming up next.", ar: "تابع مدى تقدمك ودرجات اختباراتك وما هو قادم بعد ذلك." },
  tourOutroTitle:     { en: "You're all set!", ar: "أنت جاهز الآن!" },
  tourOutroBody:      { en: "That's the whole dashboard. Enjoy the journey through the Seerah of the Prophet \ufdfa.", ar: "هذه هي لوحة التحكم بالكامل. نتمنى لك رحلة ممتعة عبر سيرة النبي ﷺ." },
  tourStepOfN:        { en: "Step {n} of {m}", ar: "الخطوة {n} من {m}" },
  tourSkip:           { en: "Skip",         ar: "تخطّ" },
  tourBack:           { en: "Back",         ar: "رجوع" },
  tourNext:           { en: "Next",         ar: "التالي" },
  tourStart:          { en: "Start tour",   ar: "ابدأ الجولة" },
  tourGetStarted:     { en: "Get started",  ar: "ابدأ الآن" },

  // ─── Past-due / email banners ─────────────────────────────────────────────
  pastDueBanner:     { en: "⚠️ Your last payment failed. Fix your card to keep access — your progress is safe.", ar: "⚠️ فشل آخر دفع. أصلح بطاقتك للحفاظ على وصولك — تقدمك محفوظ." },
  updatePayment:     { en: "Update payment →",               ar: "تحديث الدفع →"              },
  verifyEmailBanner: { en: "Please verify your email address to unlock all features.", ar: "يرجى التحقق من بريدك الإلكتروني لفتح جميع الميزات." },
  resendEmail:       { en: "Resend email",                   ar: "أعد الإرسال"                },
  dismiss:           { en: "Dismiss",                        ar: "إغلاق"                       },
};

export type UiStringKey = keyof typeof S;

/** Returns the UI string for the given lang. */
export function t(lang: CourseLang, key: UiStringKey): string {
  return S[key][lang];
}

/**
 * Returns a UI string with `{placeholder}` tokens replaced.
 * e.g. tf(lang, "stageNofM", { n: 3, m: 8 }) → "Stage 3 of 8" / "المرحلة 3 من 8"
 */
export function tf(lang: CourseLang, key: UiStringKey, vars: Record<string, string | number>): string {
  let result = S[key][lang];
  for (const [k, v] of Object.entries(vars)) {
    result = result.replace(`{${k}}`, String(v));
  }
  return result;
}

/** ERA descriptions when Arabic is selected */
export const ERA_DESCRIPTIONS_AR: Record<string, string> = {
  "Pre-Islamic Arabia":    "اكتشف العالم الذي بُعث فيه النبي ﷺ ليغيّره",
  "Birth & Early Life":   "من نسبه الشريف إلى أخلاقه قبل النبوة",
  "Beginning of Revelation": "أول الآيات، والدعوة إلى الإسلام، والمؤمنون الأوائل",
  "Makkah — Persecution": "كيف صبر المسلمون الأوائل على الأذى والرفض والتضحية",
  "The Hijrah":           "الهجرة التي غيّرت مجرى التاريخ وأسست مجتمعًا جديدًا",
  "Madinah Period":       "بناء أول مجتمع إسلامي وتأسيس الأمة",
  "Major Campaigns":      "الغزوات التي دافعت عن الإسلام وشكّلت توسعه",
  "Final Years & Legacy": "فتح مكة وحجة الوداع ووفاة النبي ﷺ",
};
