/**
 * Generates lib/part-content-data.ts by fetching all 100 parts from the local API
 * and embedding the briefingText + statementOfFactsText as hardcoded strings,
 * along with pre-rendered HTML produced by formatSeerahContent.
 *
 * Run while `npm run dev` is active:
 *   npx tsx scripts/generate-content-data.ts
 */

import fs from "fs";
import path from "path";
import { formatSeerahContent } from "../lib/text-formatter";

const BASE_URL = process.env.AUDIT_BASE_URL ?? "http://localhost:3000";
const TOTAL_PARTS = 100;
const OUT_FILE = path.join(__dirname, "..", "lib", "part-content-data.ts");

// Local Seerah-data directory — check for markdown files here first
const SEERAH_DATA_DIR =
  process.env.SEERAH_DATA_DIR ?? path.resolve(__dirname, "..", "..", "Seerah-data");

interface PartContent {
  briefingText: string | null;
  statementOfFactsText: string | null;
}

/** Try to read a local markdown briefing file for this part (better quality source). */
function readLocalMarkdownBriefing(partNum: number): string | null {
  const mdPath = path.join(
    SEERAH_DATA_DIR,
    "Briefing",
    "output_md",
    `Part ${partNum} Briefing Document.md`
  );
  if (fs.existsSync(mdPath)) {
    return fs.readFileSync(mdPath, "utf-8");
  }
  return null;
}

async function fetchPart(partNum: number, retries = 3): Promise<PartContent> {
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      const res = await fetch(`${BASE_URL}/api/part/${partNum}/content`, {
        signal: AbortSignal.timeout(15_000),
      });
      if (!res.ok) return { briefingText: null, statementOfFactsText: null };
      const data = (await res.json()) as PartContent;
      return {
        briefingText: data.briefingText ?? null,
        statementOfFactsText: data.statementOfFactsText ?? null,
      };
    } catch {
      if (attempt < retries) await new Promise(r => setTimeout(r, 400 * (attempt + 1)));
    }
  }
  return { briefingText: null, statementOfFactsText: null };
}

// Escape a string for embedding inside a TypeScript template literal
function escapeTemplateStr(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

async function main() {
  console.log(`\nFetching content for ${TOTAL_PARTS} parts from ${BASE_URL} …\n`);

  const entries: string[] = [];

  for (let partNum = 1; partNum <= TOTAL_PARTS; partNum++) {
    process.stdout.write(`  Part ${String(partNum).padStart(3)} … `);
    const content = await fetchPart(partNum);

    // Prefer local markdown file (better quality: proper headings, pipe tables, clean Unicode)
    const markdownBriefing = readLocalMarkdownBriefing(partNum);
    const briefingSource = markdownBriefing ?? content.briefingText;
    if (markdownBriefing) process.stdout.write("[md] ");

    // Pre-render HTML using the formatter so TextViewer can render it directly
    const briefingHtml = briefingSource
      ? formatSeerahContent(briefingSource)
      : null;

    const briefingText = briefingSource
      ? `\`${escapeTemplateStr(briefingSource)}\``
      : "null";
    const factsText = content.statementOfFactsText
      ? `\`${escapeTemplateStr(content.statementOfFactsText)}\``
      : "null";
    const briefingHtmlStr = briefingHtml
      ? `\`${escapeTemplateStr(briefingHtml)}\``
      : "null";

    entries.push(
      `  ${partNum}: {\n    briefingText: ${briefingText},\n    statementOfFactsText: ${factsText},\n    briefingHtml: ${briefingHtmlStr},\n  },`
    );

    const briefingLen = content.briefingText?.length ?? 0;
    const factsLen = content.statementOfFactsText?.length ?? 0;
    console.log(`briefing ${briefingLen} chars, facts ${factsLen} chars`);

    await new Promise(r => setTimeout(r, 80));
  }

  const fileContent = `// Auto-generated by scripts/generate-content-data.ts — do not edit manually.
// Regenerate with: npx tsx scripts/generate-content-data.ts (while dev server is running)

export interface PartTextContent {
  briefingText: string | null;
  statementOfFactsText: string | null;
  /** Pre-rendered HTML — use this in TextViewer to skip the formatter at runtime */
  briefingHtml: string | null;
}

export const PART_CONTENT: Record<number, PartTextContent> = {
${entries.join("\n")}
};
`;

  fs.writeFileSync(OUT_FILE, fileContent, "utf-8");

  const stats = fs.statSync(OUT_FILE);
  console.log(`\n✅  Written to lib/part-content-data.ts  (${(stats.size / 1024).toFixed(1)} KB)\n`);
}

main().catch(err => {
  console.error("Failed:", err);
  process.exit(1);
});
