/**
 * Offline HTML regeneration — does NOT need the dev server or database.
 *
 * Re-renders briefingHtml for every part from the existing briefingText using
 * the current (fixed) version of formatSeerahContent. Run this whenever
 * text-formatter.ts changes or briefingText is edited directly.
 *
 * Run:  npx tsx scripts/patch-html-only.ts
 */

import fs from "fs";
import path from "path";
import { formatSeerahContent } from "../lib/text-formatter";
import { PART_CONTENT } from "../lib/part-content-data";

const OUT_FILE = path.join(__dirname, "..", "lib", "part-content-data.ts");
const TOTAL_PARTS = 100;

function escapeTemplateStr(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

const entries: string[] = [];

for (let partNum = 1; partNum <= TOTAL_PARTS; partNum++) {
  const entry = PART_CONTENT[partNum];
  if (!entry) {
    entries.push(
      `  ${partNum}: { briefingText: null, statementOfFactsText: null, briefingHtml: null },`
    );
    process.stdout.write(`  Part ${String(partNum).padStart(3)} … (no entry)\n`);
    continue;
  }

  const { briefingText, statementOfFactsText } = entry;
  const briefingHtml = briefingText ? formatSeerahContent(briefingText) : null;

  const briefingTextStr = briefingText
    ? `\`${escapeTemplateStr(briefingText)}\``
    : "null";
  const factsStr = statementOfFactsText
    ? `\`${escapeTemplateStr(statementOfFactsText)}\``
    : "null";
  const htmlStr = briefingHtml
    ? `\`${escapeTemplateStr(briefingHtml)}\``
    : "null";

  entries.push(
    `  ${partNum}: {\n    briefingText: ${briefingTextStr},\n    statementOfFactsText: ${factsStr},\n    briefingHtml: ${htmlStr},\n  },`
  );

  process.stdout.write(`  Part ${String(partNum).padStart(3)} … ok\n`);
}

const fileContent = `// Auto-generated by scripts/generate-content-data.ts — do not edit manually.
// Regenerate with: npx tsx scripts/generate-content-data.ts (while dev server is running)
// HTML-only re-render: npx tsx scripts/patch-html-only.ts

export interface PartTextContent {
  briefingText: string | null;
  statementOfFactsText: string | null;
  /** Pre-rendered HTML — use this in TextViewer to skip the formatter at runtime */
  briefingHtml: string | null;
}

export const PART_CONTENT: Record<number, PartTextContent> = {
${entries.join("\n")}
};
`;

fs.writeFileSync(OUT_FILE, fileContent, "utf-8");
const stats = fs.statSync(OUT_FILE);
console.log(
  `\n✅  Written to lib/part-content-data.ts  (${(stats.size / 1024).toFixed(1)} KB)\n`
);
