/**
 * Re-render briefingHtml for all PART_CONTENT_AR entries from their
 * briefingText using the current formatSeerahContent (in place, no
 * translation calls). Run after any text-formatter.ts fix.
 *
 *   npx tsx scripts/regen-ar-html.ts
 */
import fs from "fs";
import path from "path";
import { formatSeerahContent } from "../lib/text-formatter";
import { PART_CONTENT_AR } from "../lib/part-content-data-ar";
import type { PartTextContent } from "../lib/part-content-data";

const outPath = path.join(process.cwd(), "lib", "part-content-data-ar.ts");

let body = `// Hardcoded Arabic translations of PART_CONTENT (English source).
// Do not load from R2 at runtime.
// Generated by scripts/merge-part-content-ar.ts from tmp/ar-parts/*.json
// HTML re-rendered by scripts/regen-ar-html.ts

import type { PartTextContent } from "./part-content-data";

export const PART_CONTENT_AR: Record<number, PartTextContent> = {
`;

const keys = Object.keys(PART_CONTENT_AR)
  .map(Number)
  .sort((a, b) => a - b);

for (const n of keys) {
  const e = PART_CONTENT_AR[n] as PartTextContent;
  const briefingHtml = e.briefingText ? formatSeerahContent(e.briefingText) : null;
  body += `  ${n}: {\n`;
  body += `    briefingText: ${JSON.stringify(e.briefingText)},\n`;
  body += `    statementOfFactsText: ${JSON.stringify(e.statementOfFactsText)},\n`;
  body += `    briefingHtml: ${JSON.stringify(briefingHtml)},\n`;
  body += `  },\n`;
}

body += `};\n`;

fs.writeFileSync(outPath, body);
console.log(`Re-rendered HTML for ${keys.length} parts → ${outPath}`);
